// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <little/interpreter/ByteCode.h>
String haxe_Serializer_run(vdynamic*);
vdynamic* haxe_Unserializer_run(String);
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$_dyn;

String little_interpreter_ByteCode_compile(hl__types__ArrayObj r0) {
	String r1;
	r1 = haxe_Serializer_run(((vdynamic*)r0));
	return r1;
}

hl__types__ArrayObj little_interpreter_ByteCode_decompile(String r0) {
	hl__types__ArrayObj r2;
	vdynamic *r1;
	r1 = haxe_Unserializer_run(r0);
	r2 = (hl__types__ArrayObj)hl_dyn_castp(&r1,&t$_dyn,&t$hl_types_ArrayObj);
	return r2;
}

