// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <little/tools/BaseOrderedMap.h>
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
#include <hl/types/ArrayObj.h>
extern hl_type t$_dyn;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
int hl_types_ArrayDyn_push(hl__types__ArrayDyn,vdynamic*);
hl__types__ArrayDyn hl_types_ArrayDyn_splice(hl__types__ArrayDyn,int,int);
vdynamic* hl_types_ArrayDyn_pop(hl__types__ArrayDyn);
#include <haxe/iterators/ArrayIterator.h>
extern hl_type t$haxe_iterators_ArrayIterator;
void haxe_iterators_ArrayIterator_new(haxe__iterators__ArrayIterator,hl__types__ArrayDyn);
extern hl_type t$vrt_ef76930;
#include <little/tools/OrderedMapKeyValueIterator.h>
extern hl_type t$little_tools_OrderedMapKeyValueIterator;
void little_tools_OrderedMapKeyValueIterator_new(little__tools__OrderedMapKeyValueIterator,hl__types__ArrayDyn,hl__types__ArrayDyn);
String little_tools_BaseOrderedMap_toString(little__tools__BaseOrderedMap);
#include <_std/String.h>
extern String s$;
extern $String g$_String;
bool Std_isOfType(vdynamic*,vdynamic*);
extern String s$b15835f;
String Std_string(vdynamic*);
String String___add__(String,String);
extern String s$e265492;
extern String s$fc763cb;
extern String s$f95b70f;
extern String s$cbb184d;

int little_tools_BaseOrderedMap_get_length(little__tools__BaseOrderedMap r0) {
	hl__types__ArrayDyn r2;
	int r1;
	r2 = r0->_ks;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayDyn_get_length(r2);
	return r1;
}

void little_tools_BaseOrderedMap_new(little__tools__BaseOrderedMap r0) {
	bool *r7;
	hl__types__ArrayObj r5;
	hl_type *r3;
	bool r6;
	hl__types__ArrayDyn r1;
	int r4;
	varray *r2;
	r3 = &t$_dyn;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r5 = hl_types_ArrayObj_alloc(r2);
	r6 = true;
	r7 = &r6;
	r1 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r5),r7);
	r0->_ks = r1;
	r3 = &t$_dyn;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r5 = hl_types_ArrayObj_alloc(r2);
	r6 = true;
	r7 = &r6;
	r1 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r5),r7);
	r0->_vs = r1;
	return;
}

vdynamic* little_tools_BaseOrderedMap_get(little__tools__BaseOrderedMap r0,vdynamic* r1) {
	hl__types__ArrayDyn r5;
	vdynamic *r2, *r7;
	int r3, r4, r6;
	r2 = NULL;
	r3 = 0;
	r5 = r0->_ks;
	if( r5 == NULL ) hl_null_access();
	r4 = hl_types_ArrayDyn_get_length(r5);
	label$e911a63_3_5:
	if( r3 >= r4 ) goto label$e911a63_3_19;
	r6 = r3;
	++r3;
	r5 = r0->_ks;
	if( r5 == NULL ) hl_null_access();
	r7 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r5->$type->vobj_proto[0])(r5,r6);
	{ int i = hl_dyn_compare((vdynamic*)r7,(vdynamic*)r1); if( i != 0 ) goto label$e911a63_3_18; };
	r5 = r0->_vs;
	if( r5 == NULL ) hl_null_access();
	r7 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r5->$type->vobj_proto[0])(r5,r6);
	r2 = r7;
	goto label$e911a63_3_19;
	label$e911a63_3_18:
	goto label$e911a63_3_5;
	label$e911a63_3_19:
	return r2;
}

void little_tools_BaseOrderedMap_set(little__tools__BaseOrderedMap r0,vdynamic* r1,vdynamic* r2) {
	hl__types__ArrayDyn r6;
	vdynamic *r8;
	int r3, r5, r7;
	r3 = 0;
	r6 = r0->_ks;
	if( r6 == NULL ) hl_null_access();
	r5 = hl_types_ArrayDyn_get_length(r6);
	label$e911a63_4_4:
	if( r3 >= r5 ) goto label$e911a63_4_20;
	r7 = r3;
	++r3;
	r6 = r0->_ks;
	if( r6 == NULL ) hl_null_access();
	r8 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r6->$type->vobj_proto[0])(r6,r7);
	{ int i = hl_dyn_compare((vdynamic*)r8,(vdynamic*)r1); if( i != 0 ) goto label$e911a63_4_19; };
	r6 = r0->_ks;
	if( r6 == NULL ) hl_null_access();
	((void (*)(hl__types__ArrayDyn,int,vdynamic*))r6->$type->vobj_proto[1])(r6,r7,r1);
	r6 = r0->_vs;
	if( r6 == NULL ) hl_null_access();
	((void (*)(hl__types__ArrayDyn,int,vdynamic*))r6->$type->vobj_proto[1])(r6,r7,r2);
	return;
	label$e911a63_4_19:
	goto label$e911a63_4_4;
	label$e911a63_4_20:
	r6 = r0->_ks;
	if( r6 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_push(r6,r1);
	r6 = r0->_vs;
	if( r6 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_push(r6,r2);
	return;
}

bool little_tools_BaseOrderedMap_remove(little__tools__BaseOrderedMap r0,vdynamic* r1) {
	bool r8;
	hl__types__ArrayDyn r4;
	vdynamic *r6;
	int r2, r3, r5, r7;
	r2 = 0;
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_get_length(r4);
	label$e911a63_5_4:
	if( r2 >= r3 ) goto label$e911a63_5_23;
	r5 = r2;
	++r2;
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r6 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r4->$type->vobj_proto[0])(r4,r5);
	{ int i = hl_dyn_compare((vdynamic*)r6,(vdynamic*)r1); if( i != 0 ) goto label$e911a63_5_22; };
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r7 = 1;
	r4 = hl_types_ArrayDyn_splice(r4,r5,r7);
	r4 = r0->_vs;
	if( r4 == NULL ) hl_null_access();
	r7 = 1;
	r4 = hl_types_ArrayDyn_splice(r4,r5,r7);
	r8 = true;
	return r8;
	label$e911a63_5_22:
	goto label$e911a63_5_4;
	label$e911a63_5_23:
	r8 = false;
	return r8;
}

bool little_tools_BaseOrderedMap_iremove(little__tools__BaseOrderedMap r0,int r1) {
	bool r7;
	hl__types__ArrayDyn r4;
	int r2, r3, r5, r6;
	r2 = 0;
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_get_length(r4);
	label$e911a63_6_4:
	if( r2 >= r3 ) goto label$e911a63_6_20;
	r5 = r2;
	++r2;
	if( r5 != r1 ) goto label$e911a63_6_19;
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r6 = 1;
	r4 = hl_types_ArrayDyn_splice(r4,r5,r6);
	r4 = r0->_vs;
	if( r4 == NULL ) hl_null_access();
	r6 = 1;
	r4 = hl_types_ArrayDyn_splice(r4,r5,r6);
	r7 = true;
	return r7;
	label$e911a63_6_19:
	goto label$e911a63_6_4;
	label$e911a63_6_20:
	r7 = false;
	return r7;
}

bool little_tools_BaseOrderedMap_clear(little__tools__BaseOrderedMap r0) {
	bool r5;
	hl__types__ArrayDyn r2;
	vdynamic *r4;
	int r1, r3;
	label$e911a63_7_0:
	r2 = r0->_ks;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayDyn_get_length(r2);
	r3 = 0;
	if( r1 == r3 ) goto label$e911a63_7_13;
	r2 = r0->_ks;
	if( r2 == NULL ) hl_null_access();
	r4 = hl_types_ArrayDyn_pop(r2);
	r2 = r0->_vs;
	if( r2 == NULL ) hl_null_access();
	r4 = hl_types_ArrayDyn_pop(r2);
	goto label$e911a63_7_0;
	label$e911a63_7_13:
	r2 = r0->_ks;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayDyn_get_length(r2);
	r3 = 0;
	if( r1 == r3 ) goto label$e911a63_7_20;
	r5 = false;
	goto label$e911a63_7_21;
	label$e911a63_7_20:
	r5 = true;
	label$e911a63_7_21:
	return r5;
}

haxe__iterators__ArrayIterator little_tools_BaseOrderedMap_keys(little__tools__BaseOrderedMap r0) {
	haxe__iterators__ArrayIterator r1;
	hl__types__ArrayDyn r2;
	r1 = (haxe__iterators__ArrayIterator)hl_alloc_obj(&t$haxe_iterators_ArrayIterator);
	r2 = r0->_ks;
	haxe_iterators_ArrayIterator_new(r1,r2);
	return r1;
}

vvirtual* little_tools_BaseOrderedMap_iterator(little__tools__BaseOrderedMap r0) {
	vvirtual *r4;
	haxe__iterators__ArrayIterator r1;
	hl__types__ArrayDyn r2;
	r1 = (haxe__iterators__ArrayIterator)hl_alloc_obj(&t$haxe_iterators_ArrayIterator);
	r2 = r0->_vs;
	haxe_iterators_ArrayIterator_new(r1,r2);
	r4 = hl_to_virtual(&t$vrt_ef76930,(vdynamic*)r1);
	return r4;
}

little__tools__OrderedMapKeyValueIterator little_tools_BaseOrderedMap_keyValueIterator(little__tools__BaseOrderedMap r0) {
	little__tools__OrderedMapKeyValueIterator r1;
	hl__types__ArrayDyn r2, r3;
	r1 = (little__tools__OrderedMapKeyValueIterator)hl_alloc_obj(&t$little_tools_OrderedMapKeyValueIterator);
	r2 = r0->_ks;
	r3 = r0->_vs;
	little_tools_OrderedMapKeyValueIterator_new(r1,r2,r3);
	return r1;
}

bool little_tools_BaseOrderedMap_has(little__tools__BaseOrderedMap r0,vdynamic* r1) {
	bool r6;
	hl__types__ArrayDyn r3;
	vdynamic *r5;
	int r2, r4;
	r2 = 0;
	r3 = r0->_ks;
	label$e911a63_11_2:
	if( r3 == NULL ) hl_null_access();
	r4 = hl_types_ArrayDyn_get_length(r3);
	if( r2 >= r4 ) goto label$e911a63_11_12;
	r5 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r3->$type->vobj_proto[0])(r3,r2);
	++r2;
	{ int i = hl_dyn_compare((vdynamic*)r1,(vdynamic*)r5); if( i != 0 ) goto label$e911a63_11_11; };
	r6 = true;
	return r6;
	label$e911a63_11_11:
	goto label$e911a63_11_2;
	label$e911a63_11_12:
	r6 = false;
	return r6;
}

bool little_tools_BaseOrderedMap_exists(little__tools__BaseOrderedMap r0,vdynamic* r1) {
	bool r2;
	r2 = little_tools_BaseOrderedMap_has(r0,r1);
	return r2;
}

vbyte* little_tools_BaseOrderedMap___string(little__tools__BaseOrderedMap r0) {
	String r2;
	vbyte *r1;
	r2 = little_tools_BaseOrderedMap_toString(r0);
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	return r1;
}

String little_tools_BaseOrderedMap_toString(little__tools__BaseOrderedMap r0) {
	$String r9;
	String r1, r6, r10, r11, r12;
	bool r7;
	hl__types__ArrayDyn r4;
	vdynamic *r8;
	int r2, r3, r5, r13, r14;
	r1 = (String)s$;
	r2 = 0;
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_get_length(r4);
	label$e911a63_14_5:
	if( r2 >= r3 ) goto label$e911a63_14_51;
	r5 = r2;
	++r2;
	r4 = r0->_vs;
	if( r4 == NULL ) hl_null_access();
	r8 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r4->$type->vobj_proto[0])(r4,r5);
	r9 = ($String)g$_String;
	r7 = Std_isOfType(r8,((vdynamic*)r9));
	if( !r7 ) goto label$e911a63_14_24;
	r6 = (String)s$b15835f;
	r4 = r0->_vs;
	if( r4 == NULL ) hl_null_access();
	r8 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r4->$type->vobj_proto[0])(r4,r5);
	r10 = Std_string(r8);
	r6 = String___add__(r6,r10);
	r10 = (String)s$b15835f;
	r6 = String___add__(r6,r10);
	goto label$e911a63_14_30;
	label$e911a63_14_24:
	r6 = (String)s$;
	r4 = r0->_vs;
	if( r4 == NULL ) hl_null_access();
	r8 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r4->$type->vobj_proto[0])(r4,r5);
	r10 = Std_string(r8);
	r6 = String___add__(r6,r10);
	label$e911a63_14_30:
	r11 = (String)s$;
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r8 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r4->$type->vobj_proto[0])(r4,r5);
	r12 = Std_string(r8);
	r11 = String___add__(r11,r12);
	r12 = (String)s$e265492;
	r11 = String___add__(r11,r12);
	r11 = String___add__(r11,r6);
	r10 = String___add__(r1,r11);
	r1 = r10;
	r4 = r0->_ks;
	if( r4 == NULL ) hl_null_access();
	r13 = hl_types_ArrayDyn_get_length(r4);
	r14 = 1;
	r13 = r13 - r14;
	if( r5 == r13 ) goto label$e911a63_14_50;
	r11 = (String)s$fc763cb;
	r10 = String___add__(r10,r11);
	r1 = r10;
	label$e911a63_14_50:
	goto label$e911a63_14_5;
	label$e911a63_14_51:
	r6 = (String)s$f95b70f;
	r6 = String___add__(r6,r1);
	r10 = (String)s$cbb184d;
	r6 = String___add__(r6,r10);
	return r6;
}

