// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <little/tools/OrderedMapKeyValueIterator.h>
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
extern hl_type t$vrt_1d300f3;
extern hl_type t$_dyn;

bool little_tools_OrderedMapKeyValueIterator_hasNext(little__tools__OrderedMapKeyValueIterator r0) {
	bool r4;
	hl__types__ArrayDyn r2;
	int r1, r3;
	r2 = r0->karray;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayDyn_get_length(r2);
	r2 = r0->varray;
	if( r2 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_get_length(r2);
	if( r1 != r3 ) goto label$427af0f_1_16;
	r1 = r0->current;
	r2 = r0->karray;
	if( r2 == NULL ) hl_null_access();
	r3 = hl_types_ArrayDyn_get_length(r2);
	if( r1 < r3 ) goto label$427af0f_1_14;
	r4 = false;
	goto label$427af0f_1_15;
	label$427af0f_1_14:
	r4 = true;
	label$427af0f_1_15:
	return r4;
	label$427af0f_1_16:
	r4 = false;
	return r4;
}

vvirtual* little_tools_OrderedMapKeyValueIterator_next(little__tools__OrderedMapKeyValueIterator r0) {
	vvirtual *r1;
	hl__types__ArrayDyn r2;
	vdynamic *r4;
	int r3, r5;
	r1 = hl_alloc_virtual(&t$vrt_1d300f3);
	r2 = r0->varray;
	if( r2 == NULL ) hl_null_access();
	r3 = r0->current;
	r4 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r2->$type->vobj_proto[0])(r2,r3);
	if( hl_vfields(r1)[1] ) *(vdynamic**)(hl_vfields(r1)[1]) = (vdynamic*)r4; else hl_dyn_setp(r1->value,297304054/*value*/,&t$_dyn,r4);
	r2 = r0->karray;
	if( r2 == NULL ) hl_null_access();
	r3 = r0->current;
	r5 = r3;
	++r3;
	r0->current = r3;
	r4 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r2->$type->vobj_proto[0])(r2,r5);
	if( hl_vfields(r1)[0] ) *(vdynamic**)(hl_vfields(r1)[0]) = (vdynamic*)r4; else hl_dyn_setp(r1->value,5343647/*key*/,&t$_dyn,r4);
	return r1;
}

void little_tools_OrderedMapKeyValueIterator_new(little__tools__OrderedMapKeyValueIterator r0,hl__types__ArrayDyn r1,hl__types__ArrayDyn r2) {
	int r3;
	r3 = 0;
	r0->current = r3;
	r0->karray = r1;
	r0->varray = r2;
	return;
}

