// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_little__tools__PrepareRun
#define INC_little__tools__PrepareRun
typedef struct _little__tools__$PrepareRun *little__tools__$PrepareRun;
typedef struct _little__tools__PrepareRun *little__tools__PrepareRun;
#include <hl/types/ArrayObj.h>
#include <little/tools/PrepareRun.h>
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


typedef struct {
	HL__ENUM_CONSTRUCT__
	hl__types__ArrayObj p0;
	hl__types__ArrayObj p1;
	hl__types__ArrayObj p2;
} Enumt$ctx_f985802;
typedef struct {
	HL__ENUM_CONSTRUCT__
	hl__types__ArrayObj p0;
	hl__types__ArrayObj p1;
	hl__types__ArrayObj p2;
	hl__types__ArrayObj p3;
} Enumt$ctx_65e518a;
struct _little__tools__$PrepareRun {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	bool prepared;
	vclosure* addTypes;
	vclosure* addFunctions;
	vclosure* addProps;
	vclosure* addSigns;
	vclosure* addConditions;
};
struct _little__tools__PrepareRun {
	hl_type *$type;
};
#endif

