// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <sys/thread/_Thread/Thread_Impl_.h>
#include <sys/thread/EventLoop.h>
#include <sys/thread/_Thread/HaxeThread.h>
sys__thread___Thread__HaxeThread sys_thread__Thread_HaxeThread_current(void);
void sys_thread_EventLoop_loop(sys__thread__EventLoop);

void sys_thread__Thread_Thread_Impl__processEvents() {
	sys__thread___Thread__HaxeThread r2;
	sys__thread__EventLoop r1;
	r2 = sys_thread__Thread_HaxeThread_current();
	if( r2 == NULL ) hl_null_access();
	r1 = r2->events;
	if( r1 == NULL ) hl_null_access();
	sys_thread_EventLoop_loop(r1);
	return;
}

