// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_sys__thread___Mutex__Mutex_Impl_
#define INC_sys__thread___Mutex__Mutex_Impl_
typedef struct _sys__thread___Mutex__$Mutex_Impl_ *sys__thread___Mutex__$Mutex_Impl_;
typedef struct _sys__thread___Mutex__Mutex_Impl_ *sys__thread___Mutex__Mutex_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>


struct _sys__thread___Mutex__$Mutex_Impl_ {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* _new;
};
struct _sys__thread___Mutex__Mutex_Impl_ {
	hl_type *$type;
};
#endif

