// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_hl___NativeArray__NativeArray_Impl_
#define INC_hl___NativeArray__NativeArray_Impl_
typedef struct _hl___NativeArray__$NativeArray_Impl_ *hl___NativeArray__$NativeArray_Impl_;
typedef struct _hl___NativeArray__NativeArray_Impl_ *hl___NativeArray__NativeArray_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _hl___NativeArray__$NativeArray_Impl_ {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _hl___NativeArray__NativeArray_Impl_ {
	hl_type *$type;
};
#endif

