// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__ds___TransformationMatrix2D__TransformationMatrix2D_Impl_
#define INC_vision__ds___TransformationMatrix2D__TransformationMatrix2D_Impl_
typedef struct _vision__ds___TransformationMatrix2D__$TransformationMatrix2D_Impl_ *vision__ds___TransformationMatrix2D__$TransformationMatrix2D_Impl_;
typedef struct _vision__ds___TransformationMatrix2D__TransformationMatrix2D_Impl_ *vision__ds___TransformationMatrix2D__TransformationMatrix2D_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <vision/ds/Array2D.h>


struct _vision__ds___TransformationMatrix2D__$TransformationMatrix2D_Impl_ {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* get_underlying;
	vclosure* get_a;
	vclosure* set_a;
	vclosure* get_b;
	vclosure* set_b;
	vclosure* get_c;
	vclosure* set_c;
	vclosure* get_d;
	vclosure* set_d;
	vclosure* get_e;
	vclosure* set_e;
	vclosure* get_f;
	vclosure* set_f;
	vclosure* get_tx;
	vclosure* set_tx;
	vclosure* get_ty;
	vclosure* set_ty;
	vclosure* _new;
	vclosure* fromMatrix2D;
};
struct _vision__ds___TransformationMatrix2D__TransformationMatrix2D_Impl_ {
	hl_type *$type;
};
#endif

