// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe__ds__IntMap
#define INC_haxe__ds__IntMap
typedef struct _haxe__ds__$IntMap *haxe__ds__$IntMap;
typedef struct _haxe__ds__IntMap *haxe__ds__IntMap;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>


struct _haxe__ds__$IntMap {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__ds__IntMap {
	hl_type *$type;
	hl_int_map* h;
	vvirtual* f$1;
};
#endif

