// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/ds/ObjectMap.h>
#include <hl/natives.h>
#include <hl/NativeArrayIterator.h>
extern hl_type t$hl_NativeArrayIterator;
void hl_NativeArrayIterator_new(hl__NativeArrayIterator,varray*);
extern hl_type t$vrt_ef76930;
String haxe_ds_ObjectMap_toString(haxe__ds__ObjectMap);
#include <_std/StringBuf.h>
extern hl_type t$StringBuf;
void StringBuf_new(StringBuf);
void StringBuf_addChar(StringBuf,int);
extern String s$fc763cb;
void StringBuf_add(StringBuf,vdynamic*);
extern String s$c8d2017;
String StringBuf_toString(StringBuf);

void haxe_ds_ObjectMap_new(haxe__ds__ObjectMap r0) {
	hl_obj_map *r1;
	r1 = hl_hoalloc();
	r0->h = r1;
	return;
}

void haxe_ds_ObjectMap_set(haxe__ds__ObjectMap r0,vdynamic* r1,vdynamic* r2) {
	hl_obj_map *r4;
	r4 = r0->h;
	hl_hoset(r4,r1,r2);
	return;
}

vdynamic* haxe_ds_ObjectMap_get(haxe__ds__ObjectMap r0,vdynamic* r1) {
	hl_obj_map *r3;
	vdynamic *r2;
	r3 = r0->h;
	r2 = hl_hoget(r3,r1);
	return r2;
}

bool haxe_ds_ObjectMap_exists(haxe__ds__ObjectMap r0,vdynamic* r1) {
	bool r2;
	hl_obj_map *r3;
	r3 = r0->h;
	r2 = hl_hoexists(r3,r1);
	return r2;
}

vvirtual* haxe_ds_ObjectMap_keys(haxe__ds__ObjectMap r0) {
	hl__NativeArrayIterator r1;
	vvirtual *r5;
	hl_obj_map *r3;
	varray *r2;
	r1 = (hl__NativeArrayIterator)hl_alloc_obj(&t$hl_NativeArrayIterator);
	r3 = r0->h;
	r2 = hl_hokeys(r3);
	hl_NativeArrayIterator_new(r1,r2);
	r5 = hl_to_virtual(&t$vrt_ef76930,(vdynamic*)r1);
	return r5;
}

vbyte* haxe_ds_ObjectMap___string(haxe__ds__ObjectMap r0) {
	String r2;
	vbyte *r1;
	r2 = haxe_ds_ObjectMap_toString(r0);
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	return r1;
}

String haxe_ds_ObjectMap_toString(haxe__ds__ObjectMap r0) {
	String r10;
	hl_obj_map *r4;
	StringBuf r1;
	vdynamic *r11;
	int r6, r7, r8, r9;
	varray *r3, *r5;
	r1 = (StringBuf)hl_alloc_obj(&t$StringBuf);
	StringBuf_new(r1);
	r4 = r0->h;
	r3 = hl_hokeys(r4);
	r4 = r0->h;
	r5 = hl_hovalues(r4);
	r6 = 91;
	StringBuf_addChar(r1,r6);
	r6 = 0;
	r7 = r3->size;
	label$07c3044_7_10:
	if( r6 >= r7 ) goto label$07c3044_7_27;
	r8 = r6;
	++r6;
	r9 = 0;
	if( r9 >= r8 ) goto label$07c3044_7_19;
	if( r1 == NULL ) hl_null_access();
	r10 = (String)s$fc763cb;
	StringBuf_add(r1,((vdynamic*)r10));
	label$07c3044_7_19:
	if( r1 == NULL ) hl_null_access();
	r11 = ((vdynamic**)(r3 + 1))[r8];
	StringBuf_add(r1,r11);
	r10 = (String)s$c8d2017;
	StringBuf_add(r1,((vdynamic*)r10));
	r11 = ((vdynamic**)(r5 + 1))[r8];
	StringBuf_add(r1,r11);
	goto label$07c3044_7_10;
	label$07c3044_7_27:
	if( r1 == NULL ) hl_null_access();
	r6 = 93;
	StringBuf_addChar(r1,r6);
	r10 = StringBuf_toString(r1);
	return r10;
}

