// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/ds/StringMap.h>
#include <hl/natives.h>
#include <haxe/ds/_StringMap/StringMapKeysIterator.h>
extern hl_type t$haxe_ds__StringMap_StringMapKeysIterator;
void haxe_ds__StringMap_StringMapKeysIterator_new(haxe__ds___StringMap__StringMapKeysIterator,hl_bytes_map*);
extern hl_type t$vrt_0a81a53;
extern hl_type t$haxe_ds_StringMap;
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_820f49a;

void haxe_ds_StringMap_new(haxe__ds__StringMap r0) {
	hl_bytes_map *r1;
	r1 = hl_hballoc();
	r0->h = r1;
	return;
}

void haxe_ds_StringMap_set(haxe__ds__StringMap r0,String r1,vdynamic* r2) {
	hl_bytes_map *r4;
	vbyte *r5;
	r4 = r0->h;
	if( r1 == NULL ) hl_null_access();
	r5 = r1->bytes;
	hl_hbset(r4,r5,r2);
	return;
}

vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap r0,String r1) {
	hl_bytes_map *r3;
	vdynamic *r2;
	vbyte *r4;
	if( r1 ) goto label$1ac35ac_3_3;
	r2 = NULL;
	return r2;
	label$1ac35ac_3_3:
	r3 = r0->h;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r2 = hl_hbget(r3,r4);
	return r2;
}

bool haxe_ds_StringMap_exists(haxe__ds__StringMap r0,String r1) {
	bool r2;
	hl_bytes_map *r3;
	vbyte *r4;
	if( r1 ) goto label$1ac35ac_4_3;
	r2 = false;
	return r2;
	label$1ac35ac_4_3:
	r3 = r0->h;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r2 = hl_hbexists(r3,r4);
	return r2;
}

vvirtual* haxe_ds_StringMap_keys(haxe__ds__StringMap r0) {
	vvirtual *r4;
	hl_bytes_map *r2;
	haxe__ds___StringMap__StringMapKeysIterator r1;
	r1 = (haxe__ds___StringMap__StringMapKeysIterator)hl_alloc_obj(&t$haxe_ds__StringMap_StringMapKeysIterator);
	r2 = r0->h;
	haxe_ds__StringMap_StringMapKeysIterator_new(r1,r2);
	r4 = hl_to_virtual(&t$vrt_0a81a53,(vdynamic*)r1);
	return r4;
}

haxe__ds__StringMap haxe_ds_StringMap_copy(haxe__ds__StringMap r0) {
	String r5;
	vvirtual *r3;
	haxe__ds__StringMap r1;
	bool r4;
	vdynamic *r6;
	r1 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r1);
	r3 = haxe_ds_StringMap_keys(r0);
	label$1ac35ac_6_3:
	if( r3 == NULL ) hl_null_access();
	if( hl_vfields(r3)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r3)[0])(r3->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r3->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$1ac35ac_6_12;
	if( hl_vfields(r3)[1] ) r5 = ((String (*)(vdynamic*))hl_vfields(r3)[1])(r3->value); else {
		r5 = (String)hl_dyn_call_obj(r3->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	if( r1 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_get(r0,r5);
	haxe_ds_StringMap_set(r1,r5,r6);
	goto label$1ac35ac_6_3;
	label$1ac35ac_6_12:
	return r1;
}

void haxe_ds_StringMap_clear(haxe__ds__StringMap r0) {
	hl_bytes_map *r2;
	r2 = r0->h;
	hl_hbclear(r2);
	return;
}

