// Generated by Haxe 4.3.4
#include <hxcpp.h>

#ifndef INCLUDED_vision_ds_Array2D
#include <vision/ds/Array2D.h>
#endif
#ifndef INCLUDED_vision_ds__TransformationMatrix2D_TransformationMatrix2D_Impl_
#include <vision/ds/_TransformationMatrix2D/TransformationMatrix2D_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_14_get_underlying,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_underlying",0x4b67414c,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_underlying","vision/ds/TransformationMatrix2D.hx",14,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_30_get_a,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_a",0x25821552,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_a","vision/ds/TransformationMatrix2D.hx",30,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_31_set_a,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_a",0x0e510b5e,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_a","vision/ds/TransformationMatrix2D.hx",31,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_47_get_b,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_b",0x25821553,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_b","vision/ds/TransformationMatrix2D.hx",47,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_48_set_b,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_b",0x0e510b5f,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_b","vision/ds/TransformationMatrix2D.hx",48,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_64_get_c,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_c",0x25821554,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_c","vision/ds/TransformationMatrix2D.hx",64,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_65_set_c,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_c",0x0e510b60,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_c","vision/ds/TransformationMatrix2D.hx",65,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_81_get_d,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_d",0x25821555,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_d","vision/ds/TransformationMatrix2D.hx",81,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_82_set_d,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_d",0x0e510b61,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_d","vision/ds/TransformationMatrix2D.hx",82,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_104_get_e,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_e",0x25821556,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_e","vision/ds/TransformationMatrix2D.hx",104,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_105_set_e,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_e",0x0e510b62,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_e","vision/ds/TransformationMatrix2D.hx",105,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_127_get_f,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_f",0x25821557,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_f","vision/ds/TransformationMatrix2D.hx",127,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_128_set_f,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_f",0x0e510b63,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_f","vision/ds/TransformationMatrix2D.hx",128,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_144_get_tx,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_tx",0xac50a373,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_tx","vision/ds/TransformationMatrix2D.hx",144,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_145_set_tx,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_tx",0x7898f7e7,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_tx","vision/ds/TransformationMatrix2D.hx",145,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_161_get_ty,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","get_ty",0xac50a374,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.get_ty","vision/ds/TransformationMatrix2D.hx",161,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_162_set_ty,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","set_ty",0x7898f7e8,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.set_ty","vision/ds/TransformationMatrix2D.hx",162,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_164__new,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","_new",0x30dca687,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_._new","vision/ds/TransformationMatrix2D.hx",164,0x27cc56e9)
HX_LOCAL_STACK_FRAME(_hx_pos_58e9b6184447e129_212_fromMatrix2D,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_","fromMatrix2D",0x8a163703,"vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_.fromMatrix2D","vision/ds/TransformationMatrix2D.hx",212,0x27cc56e9)
namespace vision{
namespace ds{
namespace _TransformationMatrix2D{

void TransformationMatrix2D_Impl__obj::__construct() { }

Dynamic TransformationMatrix2D_Impl__obj::__CreateEmpty() { return new TransformationMatrix2D_Impl__obj; }

void *TransformationMatrix2D_Impl__obj::_hx_vtable = 0;

Dynamic TransformationMatrix2D_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< TransformationMatrix2D_Impl__obj > _hx_result = new TransformationMatrix2D_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool TransformationMatrix2D_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x781cfd20;
}

 ::vision::ds::Array2D TransformationMatrix2D_Impl__obj::get_underlying( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_14_get_underlying)
HXDLIN(  14)		return this1;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_underlying,return )

Float TransformationMatrix2D_Impl__obj::get_a( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_30_get_a)
HXDLIN(  30)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  30)		return ( (Float)(_this->inner->__get((0 * _this->width))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_a,return )

Float TransformationMatrix2D_Impl__obj::set_a( ::vision::ds::Array2D this1,Float a){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_31_set_a)
HXDLIN(  31)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  31)		return (_this->inner->set((0 * _this->width),a));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_a,return )

Float TransformationMatrix2D_Impl__obj::get_b( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_47_get_b)
HXDLIN(  47)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  47)		return ( (Float)(_this->inner->__get(_this->width)) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_b,return )

Float TransformationMatrix2D_Impl__obj::set_b( ::vision::ds::Array2D this1,Float b){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_48_set_b)
HXDLIN(  48)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  48)		return (_this->inner->set(_this->width,b));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_b,return )

Float TransformationMatrix2D_Impl__obj::get_c( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_64_get_c)
HXDLIN(  64)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  64)		return ( (Float)(_this->inner->__get(((0 * _this->width) + 1))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_c,return )

Float TransformationMatrix2D_Impl__obj::set_c( ::vision::ds::Array2D this1,Float c){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_65_set_c)
HXDLIN(  65)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  65)		return (_this->inner->set((1 + (0 * _this->width)),c));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_c,return )

Float TransformationMatrix2D_Impl__obj::get_d( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_81_get_d)
HXDLIN(  81)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  81)		return ( (Float)(_this->inner->__get((_this->width + 1))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_d,return )

Float TransformationMatrix2D_Impl__obj::set_d( ::vision::ds::Array2D this1,Float d){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_82_set_d)
HXDLIN(  82)		 ::vision::ds::Array2D _this = this1;
HXDLIN(  82)		return (_this->inner->set((1 + _this->width),d));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_d,return )

Float TransformationMatrix2D_Impl__obj::get_e( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_104_get_e)
HXDLIN( 104)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 104)		return ( (Float)(_this->inner->__get((2 * _this->width))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_e,return )

Float TransformationMatrix2D_Impl__obj::set_e( ::vision::ds::Array2D this1,Float e){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_105_set_e)
HXDLIN( 105)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 105)		return (_this->inner->set((2 * _this->width),e));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_e,return )

Float TransformationMatrix2D_Impl__obj::get_f( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_127_get_f)
HXDLIN( 127)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 127)		return ( (Float)(_this->inner->__get(((2 * _this->width) + 1))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_f,return )

Float TransformationMatrix2D_Impl__obj::set_f( ::vision::ds::Array2D this1,Float f){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_128_set_f)
HXDLIN( 128)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 128)		return (_this->inner->set((1 + (2 * _this->width)),f));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_f,return )

Float TransformationMatrix2D_Impl__obj::get_tx( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_144_get_tx)
HXDLIN( 144)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 144)		return ( (Float)(_this->inner->__get(((0 * _this->width) + 2))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_tx,return )

Float TransformationMatrix2D_Impl__obj::set_tx( ::vision::ds::Array2D this1,Float tx){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_145_set_tx)
HXDLIN( 145)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 145)		return (_this->inner->set((2 + (0 * _this->width)),tx));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_tx,return )

Float TransformationMatrix2D_Impl__obj::get_ty( ::vision::ds::Array2D this1){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_161_get_ty)
HXDLIN( 161)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 161)		return ( (Float)(_this->inner->__get((_this->width + 2))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,get_ty,return )

Float TransformationMatrix2D_Impl__obj::set_ty( ::vision::ds::Array2D this1,Float ty){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_162_set_ty)
HXDLIN( 162)		 ::vision::ds::Array2D _this = this1;
HXDLIN( 162)		return (_this->inner->set((2 + _this->width),ty));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TransformationMatrix2D_Impl__obj,set_ty,return )

 ::vision::ds::Array2D TransformationMatrix2D_Impl__obj::_new( ::vision::ds::Array2D m){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_164__new)
HXDLIN( 164)		return m;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,_new,return )

 ::vision::ds::Array2D TransformationMatrix2D_Impl__obj::fromMatrix2D( ::vision::ds::Array2D m){
            	HX_STACKFRAME(&_hx_pos_58e9b6184447e129_212_fromMatrix2D)
HXDLIN( 212)		return ::vision::ds::_TransformationMatrix2D::TransformationMatrix2D_Impl__obj::_new(m);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TransformationMatrix2D_Impl__obj,fromMatrix2D,return )


TransformationMatrix2D_Impl__obj::TransformationMatrix2D_Impl__obj()
{
}

bool TransformationMatrix2D_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"_new") ) { outValue = _new_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"get_a") ) { outValue = get_a_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_a") ) { outValue = set_a_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_b") ) { outValue = get_b_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_b") ) { outValue = set_b_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_c") ) { outValue = get_c_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_c") ) { outValue = set_c_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_d") ) { outValue = get_d_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_d") ) { outValue = set_d_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_e") ) { outValue = get_e_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_e") ) { outValue = set_e_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_f") ) { outValue = get_f_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_f") ) { outValue = set_f_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"get_tx") ) { outValue = get_tx_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_tx") ) { outValue = set_tx_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_ty") ) { outValue = get_ty_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_ty") ) { outValue = set_ty_dyn(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"fromMatrix2D") ) { outValue = fromMatrix2D_dyn(); return true; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"get_underlying") ) { outValue = get_underlying_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *TransformationMatrix2D_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *TransformationMatrix2D_Impl__obj_sStaticStorageInfo = 0;
#endif

::hx::Class TransformationMatrix2D_Impl__obj::__mClass;

static ::String TransformationMatrix2D_Impl__obj_sStaticFields[] = {
	HX_("get_underlying",a6,84,a6,cf),
	HX_("get_a",38,a5,60,91),
	HX_("set_a",44,9b,2f,7a),
	HX_("get_b",39,a5,60,91),
	HX_("set_b",45,9b,2f,7a),
	HX_("get_c",3a,a5,60,91),
	HX_("set_c",46,9b,2f,7a),
	HX_("get_d",3b,a5,60,91),
	HX_("set_d",47,9b,2f,7a),
	HX_("get_e",3c,a5,60,91),
	HX_("set_e",48,9b,2f,7a),
	HX_("get_f",3d,a5,60,91),
	HX_("set_f",49,9b,2f,7a),
	HX_("get_tx",cd,fc,2f,a3),
	HX_("set_tx",41,51,78,6f),
	HX_("get_ty",ce,fc,2f,a3),
	HX_("set_ty",42,51,78,6f),
	HX_("_new",61,15,1f,3f),
	HX_("fromMatrix2D",dd,0f,0a,07),
	::String(null())
};

void TransformationMatrix2D_Impl__obj::__register()
{
	TransformationMatrix2D_Impl__obj _hx_dummy;
	TransformationMatrix2D_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("vision.ds._TransformationMatrix2D.TransformationMatrix2D_Impl_",08,61,0c,b0);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &TransformationMatrix2D_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(TransformationMatrix2D_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< TransformationMatrix2D_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = TransformationMatrix2D_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = TransformationMatrix2D_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace vision
} // end namespace ds
} // end namespace _TransformationMatrix2D
