// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe__io__BytesBuffer
#define INC_haxe__io__BytesBuffer
typedef struct _haxe__io__$BytesBuffer *haxe__io__$BytesBuffer;
typedef struct _haxe__io__BytesBuffer *haxe__io__BytesBuffer;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _haxe__io__$BytesBuffer {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__io__BytesBuffer {
	hl_type *$type;
	vbyte* b;
	int pos;
	int size;
};
#endif

