// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/io/Bytes.h>
#include <haxe/io/Error.h>
extern venum* g$haxe_io_Error_OutsideBounds;
#include <hl/natives.h>
extern venum* g$haxe_io_Encoding_RawNative;
extern hl_type t$String;
String String_fromUTF8(vbyte*);
String haxe_io_Bytes_toString(haxe__io__Bytes);
extern hl_type t$haxe_io_Bytes;
extern venum* g$haxe_io_Encoding_UTF8;
vbyte* hl__Bytes_Bytes_Impl__sub(vbyte*,int,int);

void haxe_io_Bytes_new(haxe__io__Bytes r0,vbyte* r1,int r2) {
	r0->b = r1;
	r0->length = r2;
	return;
}

int haxe_io_Bytes_get(haxe__io__Bytes r0,int r1) {
	vbyte *r4;
	int r2, r3;
	r3 = r0->length;
	if( ((unsigned)r1) < ((unsigned)r3) ) goto label$f9d86ae_2_4;
	r2 = 0;
	return r2;
	label$f9d86ae_2_4:
	r4 = r0->b;
	r2 = *(unsigned char*)(r4 + r1);
	return r2;
}

void haxe_io_Bytes_set(haxe__io__Bytes r0,int r1,int r2) {
	venum *r5;
	vbyte *r6;
	int r4;
	r4 = r0->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$f9d86ae_3_4;
	r5 = (venum*)g$haxe_io_Error_OutsideBounds;
	hl_throw((vdynamic*)r5);
	label$f9d86ae_3_4:
	r6 = r0->b;
	*(unsigned char*)(r6 + r1) = (unsigned char)r2;
	return;
}

void haxe_io_Bytes_blit(haxe__io__Bytes r0,int r1,haxe__io__Bytes r2,int r3,int r4) {
	venum *r8;
	vbyte *r9, *r10;
	int r6, r7;
	r7 = 0;
	if( r1 < r7 ) goto label$f9d86ae_4_15;
	r7 = 0;
	if( r4 < r7 ) goto label$f9d86ae_4_15;
	r6 = r1 + r4;
	r7 = r0->length;
	if( ((unsigned)r7) < ((unsigned)r6) ) goto label$f9d86ae_4_15;
	r7 = 0;
	if( r3 < r7 ) goto label$f9d86ae_4_15;
	r7 = 0;
	if( r4 < r7 ) goto label$f9d86ae_4_15;
	r6 = r3 + r4;
	if( r2 == NULL ) hl_null_access();
	r7 = r2->length;
	if( ((unsigned)r7) >= ((unsigned)r6) ) goto label$f9d86ae_4_17;
	label$f9d86ae_4_15:
	r8 = (venum*)g$haxe_io_Error_OutsideBounds;
	hl_throw((vdynamic*)r8);
	label$f9d86ae_4_17:
	r9 = r0->b;
	r10 = r2->b;
	hl_bytes_blit(r9,r1,r10,r3,r4);
	return;
}

void haxe_io_Bytes_fill(haxe__io__Bytes r0,int r1,int r2,int r3) {
	venum *r7;
	vbyte *r8;
	int r5, r6;
	r6 = 0;
	if( r1 < r6 ) goto label$f9d86ae_5_7;
	r6 = 0;
	if( r2 < r6 ) goto label$f9d86ae_5_7;
	r5 = r1 + r2;
	r6 = r0->length;
	if( ((unsigned)r6) >= ((unsigned)r5) ) goto label$f9d86ae_5_9;
	label$f9d86ae_5_7:
	r7 = (venum*)g$haxe_io_Error_OutsideBounds;
	hl_throw((vdynamic*)r7);
	label$f9d86ae_5_9:
	r8 = r0->b;
	hl_bytes_fill(r8,r1,r2,r3);
	return;
}

double haxe_io_Bytes_getDouble(haxe__io__Bytes r0,int r1) {
	double r4;
	vbyte *r5;
	int r2, r3;
	r3 = 7;
	r2 = r1 + r3;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$f9d86ae_6_6;
	r4 = 0.;
	return r4;
	label$f9d86ae_6_6:
	r5 = r0->b;
	r4 = *(double*)(r5 + r1);
	return r4;
}

void haxe_io_Bytes_setDouble(haxe__io__Bytes r0,int r1,double r2) {
	venum *r6;
	vbyte *r7;
	int r4, r5;
	r5 = 7;
	r4 = r1 + r5;
	r5 = r0->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$f9d86ae_7_6;
	r6 = (venum*)g$haxe_io_Error_OutsideBounds;
	hl_throw((vdynamic*)r6);
	label$f9d86ae_7_6:
	r7 = r0->b;
	*(double*)(r7 + r1) = r2;
	return;
}

int haxe_io_Bytes_getInt32(haxe__io__Bytes r0,int r1) {
	vbyte *r4;
	int r2, r3;
	r3 = 3;
	r2 = r1 + r3;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$f9d86ae_8_6;
	r2 = 0;
	return r2;
	label$f9d86ae_8_6:
	r4 = r0->b;
	r2 = *(int*)(r4 + r1);
	return r2;
}

void haxe_io_Bytes_setInt32(haxe__io__Bytes r0,int r1,int r2) {
	venum *r6;
	vbyte *r7;
	int r4, r5;
	r5 = 3;
	r4 = r1 + r5;
	r5 = r0->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$f9d86ae_9_6;
	r6 = (venum*)g$haxe_io_Error_OutsideBounds;
	hl_throw((vdynamic*)r6);
	label$f9d86ae_9_6:
	r7 = r0->b;
	*(int*)(r7 + r1) = r2;
	return;
}

String haxe_io_Bytes_getString(haxe__io__Bytes r0,int r1,int r2,venum* r3) {
	String r11;
	venum *r7, *r10;
	vbyte *r8, *r9;
	int r5, r6;
	r6 = 0;
	if( r1 < r6 ) goto label$f9d86ae_10_7;
	r6 = 0;
	if( r2 < r6 ) goto label$f9d86ae_10_7;
	r5 = r1 + r2;
	r6 = r0->length;
	if( ((unsigned)r6) >= ((unsigned)r5) ) goto label$f9d86ae_10_9;
	label$f9d86ae_10_7:
	r7 = (venum*)g$haxe_io_Error_OutsideBounds;
	hl_throw((vdynamic*)r7);
	label$f9d86ae_10_9:
	r6 = 2;
	r5 = r2 + r6;
	r8 = hl_alloc_bytes(r5);
	r5 = 0;
	r9 = r0->b;
	hl_bytes_blit(r8,r5,r9,r1,r2);
	r6 = 0;
	*(unsigned char*)(r8 + r2) = (unsigned char)r6;
	r6 = 1;
	r5 = r2 + r6;
	r6 = 0;
	*(unsigned char*)(r8 + r5) = (unsigned char)r6;
	r10 = (venum*)g$haxe_io_Encoding_RawNative;
	if( r3 != r10 ) goto label$f9d86ae_10_29;
	r11 = (String)hl_alloc_obj(&t$String);
	r11->bytes = r8;
	r5 = 0;
	r5 = hl_ucs2length(r8,r5);
	r11->length = r5;
	return r11;
	label$f9d86ae_10_29:
	r11 = String_fromUTF8(r8);
	return r11;
}

vbyte* haxe_io_Bytes___string(haxe__io__Bytes r0) {
	String r2;
	vbyte *r1;
	r2 = haxe_io_Bytes_toString(r0);
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	return r1;
}

String haxe_io_Bytes_toString(haxe__io__Bytes r0) {
	String r1;
	venum *r4;
	int r2, r3;
	r2 = 0;
	r3 = r0->length;
	r4 = NULL;
	r1 = haxe_io_Bytes_getString(r0,r2,r3,r4);
	return r1;
}

haxe__io__Bytes haxe_io_Bytes_alloc(int r0) {
	haxe__io__Bytes r5;
	int r2, r4;
	vbyte *r1;
	r1 = hl_alloc_bytes(r0);
	r2 = 0;
	r4 = 0;
	hl_bytes_fill(r1,r2,r0,r4);
	r5 = (haxe__io__Bytes)hl_alloc_obj(&t$haxe_io_Bytes);
	haxe_io_Bytes_new(r5,r1,r0);
	return r5;
}

haxe__io__Bytes haxe_io_Bytes_ofString(String r0,venum* r1) {
	venum *r3;
	haxe__io__Bytes r8;
	int *r7;
	vbyte *r5;
	int r4, r6, r9, r10;
	if( r1 ) goto label$f9d86ae_14_3;
	r3 = (venum*)g$haxe_io_Encoding_UTF8;
	r1 = r3;
	label$f9d86ae_14_3:
	if( r1 == NULL ) hl_null_access();
	r4 = HL__ENUM_INDEX__(r1);
	switch(r4) {
		default:
			goto label$f9d86ae_14_29;
		case 0:
			r4 = 0;
			if( r0 == NULL ) hl_null_access();
			r5 = r0->bytes;
			r6 = r0->length;
			r7 = &r4;
			r5 = hl_utf16_to_utf8(r5,r6,r7);
			r8 = (haxe__io__Bytes)hl_alloc_obj(&t$haxe_io_Bytes);
			haxe_io_Bytes_new(r8,r5,r4);
			return r8;
		case 1:
			r8 = (haxe__io__Bytes)hl_alloc_obj(&t$haxe_io_Bytes);
			if( r0 == NULL ) hl_null_access();
			r5 = r0->bytes;
			r6 = 0;
			r9 = r0->length;
			r10 = 1;
			r9 = r9 << r10;
			r5 = hl__Bytes_Bytes_Impl__sub(r5,r6,r9);
			r6 = r0->length;
			r9 = 1;
			r6 = r6 << r9;
			haxe_io_Bytes_new(r8,r5,r6);
			return r8;
	}
	label$f9d86ae_14_29:
	r8 = NULL;
	return r8;
}

