// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe__io__Eof
#define INC_haxe__io__Eof
typedef struct _haxe__io__$Eof *haxe__io__$Eof;
typedef struct _haxe__io__Eof *haxe__io__Eof;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _haxe__io__$Eof {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe__io__Eof {
	hl_type *$type;
};
#endif

