// Generated by Haxe 4.3.1
#ifndef INCLUDED_little_lexer_Lexer
#define INCLUDED_little_lexer_Lexer

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(little,lexer,Lexer)
HX_DECLARE_CLASS2(little,lexer,LexerTokens)

namespace little{
namespace lexer{


class HXCPP_CLASS_ATTRIBUTES Lexer_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Lexer_obj OBJ_;
		Lexer_obj();

	public:
		enum { _hx_ClassId = 0x6ee2cb96 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="little.lexer.Lexer")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"little.lexer.Lexer"); }

		inline static ::hx::ObjectPtr< Lexer_obj > __new() {
			::hx::ObjectPtr< Lexer_obj > __this = new Lexer_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Lexer_obj > __alloc(::hx::Ctx *_hx_ctx) {
			Lexer_obj *__this = (Lexer_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Lexer_obj), false, "little.lexer.Lexer"));
			*(void **)__this = Lexer_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Lexer_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Lexer",ec,09,92,05); }

		static ::Array< ::Dynamic> lex(::String code);
		static ::Dynamic lex_dyn();

		static ::Array< ::Dynamic> separateBooleanIdentifiers(::Array< ::Dynamic> tokens);
		static ::Dynamic separateBooleanIdentifiers_dyn();

		static ::Array< ::Dynamic> mergeOrSplitKnownSigns(::Array< ::Dynamic> tokens);
		static ::Dynamic mergeOrSplitKnownSigns_dyn();

};

} // end namespace little
} // end namespace lexer

#endif /* INCLUDED_little_lexer_Lexer */ 
