// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__helpers__TextDrawer
#define INC_vision__helpers__TextDrawer
typedef struct _vision__helpers__$TextDrawer *vision__helpers__$TextDrawer;
typedef struct _vision__helpers__TextDrawer *vision__helpers__TextDrawer;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Bytes.h>


struct _vision__helpers__$TextDrawer {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* reportDependencies;
	vclosure* drawTextOnImage;
};
struct _vision__helpers__TextDrawer {
	hl_type *$type;
};
#endif

