// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_little__interpreter__memory__ExternalInterfacing
#define INC_little__interpreter__memory__ExternalInterfacing
typedef struct _little__interpreter__memory__$ExternalInterfacing *little__interpreter__memory__$ExternalInterfacing;
typedef struct _little__interpreter__memory__ExternalInterfacing *little__interpreter__memory__ExternalInterfacing;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <little/interpreter/memory/Memory.h>
#include <haxe/ds/StringMap.h>
#include <haxe/ds/IntMap.h>
#include <little/interpreter/memory/ExtTree.h>


struct _little__interpreter__memory__$ExternalInterfacing {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _little__interpreter__memory__ExternalInterfacing {
	hl_type *$type;
	little__interpreter__memory__Memory parent;
	haxe__ds__StringMap externToPointer;
	haxe__ds__IntMap pointerToExtern;
	little__interpreter__memory__ExtTree instanceProperties;
	little__interpreter__memory__ExtTree globalProperties;
};
#endif

