// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_little__interpreter__memory__OperatorType
#define INC_little__interpreter__memory__OperatorType
typedef struct _little__interpreter__memory__$OperatorType *little__interpreter__memory__$OperatorType;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>


struct _little__interpreter__memory__$OperatorType {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___ename__;
	hl_bytes_map* _hx___emap__;
	hl__types__ArrayObj _hx___constructs__;
	varray* _hx___evalues__;
};
#endif

