// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__algorithms__BilinearInterpolation
#define INC_vision__algorithms__BilinearInterpolation
typedef struct _vision__algorithms__$BilinearInterpolation *vision__algorithms__$BilinearInterpolation;
typedef struct _vision__algorithms__BilinearInterpolation *vision__algorithms__BilinearInterpolation;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Bytes.h>


struct _vision__algorithms__$BilinearInterpolation {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* interpolate;
	vclosure* interpolateMissingPixels;
};
struct _vision__algorithms__BilinearInterpolation {
	hl_type *$type;
};
#endif

