// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__algorithms__Cramer
#define INC_vision__algorithms__Cramer
typedef struct _vision__algorithms__$Cramer *vision__algorithms__$Cramer;
typedef struct _vision__algorithms__Cramer *vision__algorithms__Cramer;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <vision/ds/Array2D.h>
#include <hl/types/ArrayBytes_Float.h>


struct _vision__algorithms__$Cramer {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* solveVariablesFor;
};
struct _vision__algorithms__Cramer {
	hl_type *$type;
};
#endif

