// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <vision/algorithms/Cramer.h>
#include <hl/types/ArrayDyn.h>
#include <hl/types/ArrayObj.h>
extern String s$;
extern hl_type t$vision_ds_Array2D;
void vision_ds_Array2D_new(vision__ds__Array2D,int,int,vdynamic*);
extern hl_type t$hl_types_ArrayBytes_Float;
extern hl_type t$hl_types_ArrayDyn;
hl__types__ArrayBytes_Float hl_types_ArrayBytes_Float_copy(hl__types__ArrayBytes_Float);
#include <hl/natives.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
hl__types__ArrayObj vision_ds_Array2D_to2DArray(vision__ds__Array2D);
extern hl_type t$_i32;
vdynamic* hl_types_ArrayObj_shift(hl__types__ArrayObj);
extern hl_type t$_dyn;
vdynamic* hl_types_ArrayObj_pop(hl__types__ArrayObj);
vdynamic* hl_types_ArrayBytes_Float_shift(hl__types__ArrayBytes_Float);
vdynamic* hl_types_ArrayBytes_Float_pop(hl__types__ArrayBytes_Float);
hl__types__ArrayBytes_Float hl_types_ArrayBytes_Float_concat(hl__types__ArrayBytes_Float,hl__types__ArrayBytes_Float);
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
extern hl_type t$nul_f64;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
void hl_types_ArrayBytes_Float_resize(hl__types__ArrayBytes_Float,int);
double vision_ds__Matrix2D_Matrix2D_Impl__getDeterminant(vision__ds__Array2D);
int hl_types_ArrayBytes_Float_push(hl__types__ArrayBytes_Float,double);

hl__types__ArrayBytes_Float vision_algorithms_Cramer_solveVariablesFor(vision__ds__Array2D r0,hl__types__ArrayBytes_Float r1) {
	String r7;
	hl__types__ArrayObj r32, r36, r41, r44, r45;
	vision__ds__Array2D r4, r9, r12, r13, r14, r19, r21, r40;
	hl_type *r43;
	hl__types__ArrayBytes_Float r6, r16, r26, r39;
	double r27, r29, r46, r47, r49, r56, r57, r58, r60;
	hl__types__ArrayDyn r11;
	vdynamic *r8, *r10, *r30, *r31, *r33, *r50, *r51;
	varray *r37;
	vbyte *r15;
	int r3, r5, r17, r18, r20, r22, r23, r24, r25, r28, r34, r35, r38, r42, r48, r52, r53, r54, r55, r59;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->width;
	if( r1 == NULL ) hl_null_access();
	r5 = r1->length;
	if( r3 == r5 ) goto label$258c0f8_1_7;
	r7 = (String)s$;
	hl_throw((vdynamic*)r7);
	label$258c0f8_1_7:
	r3 = r0->height;
	r5 = r1->length;
	if( r3 == r5 ) goto label$258c0f8_1_12;
	r7 = (String)s$;
	hl_throw((vdynamic*)r7);
	label$258c0f8_1_12:
	r4 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
	r3 = r0->width;
	r5 = r0->height;
	r10 = NULL;
	vision_ds_Array2D_new(r4,r3,r5,((vdynamic*)r10));
	r11 = r0->inner;
	r6 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
	if( r6 == NULL ) hl_null_access();
	r6 = hl_types_ArrayBytes_Float_copy(r6);
	r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r6,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayDyn);
	r4->inner = r11;
	r9 = r4;
	r12 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
	r3 = r4->width;
	r5 = r4->height;
	r10 = NULL;
	vision_ds_Array2D_new(r12,r3,r5,((vdynamic*)r10));
	r11 = r4->inner;
	r6 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
	if( r6 == NULL ) hl_null_access();
	r6 = hl_types_ArrayBytes_Float_copy(r6);
	r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r6,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayDyn);
	r12->inner = r11;
	r3 = 0;
	r15 = hl_alloc_bytes(r3);
	r3 = 0;
	r3 = 0;
	r6 = hl_types_ArrayBase_allocF64(r15,r3);
	r3 = 0;
	r5 = r1->length;
	label$258c0f8_1_42:
	if( r3 >= r5 ) goto label$258c0f8_1_1243;
	r17 = r3;
	++r3;
	r14 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
	if( r9 == NULL ) hl_null_access();
	r18 = r9->width;
	r20 = r9->height;
	r10 = NULL;
	vision_ds_Array2D_new(r14,r18,r20,((vdynamic*)r10));
	r11 = r9->inner;
	r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
	if( r16 == NULL ) hl_null_access();
	r16 = hl_types_ArrayBytes_Float_copy(r16);
	r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayDyn);
	r14->inner = r11;
	r13 = r14;
	if( r1 == NULL ) hl_null_access();
	r18 = r1->length;
	r20 = r14->height;
	if( r18 >= r20 ) goto label$258c0f8_1_65;
	r7 = (String)s$;
	hl_throw((vdynamic*)r7);
	label$258c0f8_1_65:
	r18 = 0;
	r20 = r14->height;
	label$258c0f8_1_67:
	if( r18 >= r20 ) goto label$258c0f8_1_95;
	r22 = r18;
	++r18;
	if( r13 == NULL ) hl_null_access();
	r11 = r13->inner;
	r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
	if( r16 == NULL ) hl_null_access();
	r25 = r13->width;
	r24 = r22 * r25;
	r23 = r17 + r24;
	if( r1 == NULL ) hl_null_access();
	r25 = r1->length;
	if( ((unsigned)r22) < ((unsigned)r25) ) goto label$258c0f8_1_83;
	r27 = 0.;
	goto label$258c0f8_1_87;
	label$258c0f8_1_83:
	r15 = r1->bytes;
	r25 = 3;
	r25 = r22 << r25;
	r27 = *(double*)(r15 + r25);
	label$258c0f8_1_87:
	r24 = r16->length;
	if( ((unsigned)r23) < ((unsigned)r24) ) goto label$258c0f8_1_90;
	hl_types_ArrayBytes_Float___expand(r16,r23);
	label$258c0f8_1_90:
	r15 = r16->bytes;
	r24 = 3;
	r24 = r23 << r24;
	*(double*)(r15 + r24) = r27;
	goto label$258c0f8_1_67;
	label$258c0f8_1_95:
	if( r13 == NULL ) hl_null_access();
	r18 = r13->width;
	switch(r18) {
		default:
			r27 = 0.;
			r20 = 1;
			r22 = 0;
			r23 = r13->width;
			label$258c0f8_1_102:
			if( r22 >= r23 ) goto label$258c0f8_1_586;
			r24 = r22;
			++r22;
			if( r13 == NULL ) hl_null_access();
			r11 = r13->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r25 = 0;
			r28 = r13->width;
			r25 = r25 * r28;
			r25 = r25 + r24;
			r28 = r16->length;
			if( ((unsigned)r25) < ((unsigned)r28) ) goto label$258c0f8_1_118;
			r29 = 0.;
			goto label$258c0f8_1_122;
			label$258c0f8_1_118:
			r15 = r16->bytes;
			r28 = 3;
			r28 = r25 << r28;
			r29 = *(double*)(r15 + r28);
			label$258c0f8_1_122:
			r30 = NULL;
			r31 = NULL;
			r32 = vision_ds_Array2D_to2DArray(r13);
			if( r30 ) goto label$258c0f8_1_129;
			r25 = r13->width;
			r33 = hl_alloc_dynamic(&t$_i32);
			r33->v.i = r25;
			r30 = r33;
			label$258c0f8_1_129:
			if( r31 ) goto label$258c0f8_1_133;
			r25 = r13->height;
			r33 = hl_alloc_dynamic(&t$_i32);
			r33->v.i = r25;
			r31 = r33;
			label$258c0f8_1_133:
			r25 = 0;
			r28 = 1;
			label$258c0f8_1_135:
			if( r25 >= r28 ) goto label$258c0f8_1_142;
			++r25;
			if( r32 == NULL ) hl_null_access();
			r8 = hl_types_ArrayObj_shift(r32);
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			goto label$258c0f8_1_135;
			label$258c0f8_1_142:
			r25 = r30 ? r30->v.i : 0;
			if( r32 == NULL ) hl_null_access();
			r28 = r32->length;
			label$258c0f8_1_145:
			if( r25 >= r28 ) goto label$258c0f8_1_152;
			++r25;
			if( r32 == NULL ) hl_null_access();
			r8 = hl_types_ArrayObj_pop(r32);
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			goto label$258c0f8_1_145;
			label$258c0f8_1_152:
			r25 = 0;
			label$258c0f8_1_153:
			if( r32 == NULL ) hl_null_access();
			r34 = r32->length;
			if( r25 >= r34 ) goto label$258c0f8_1_183;
			r34 = r32->length;
			if( ((unsigned)r25) < ((unsigned)r34) ) goto label$258c0f8_1_161;
			r16 = NULL;
			goto label$258c0f8_1_164;
			label$258c0f8_1_161:
			r37 = r32->array;
			r8 = ((vdynamic**)(r37 + 1))[r25];
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			label$258c0f8_1_164:
			++r25;
			r28 = 0;
			r34 = 0;
			label$258c0f8_1_167:
			if( r28 >= r34 ) goto label$258c0f8_1_173;
			++r28;
			if( r16 == NULL ) hl_null_access();
			r10 = hl_types_ArrayBytes_Float_shift(r16);
			goto label$258c0f8_1_167;
			label$258c0f8_1_173:
			r28 = r31 ? r31->v.i : 0;
			if( r16 == NULL ) hl_null_access();
			r34 = r16->length;
			label$258c0f8_1_176:
			if( r28 >= r34 ) goto label$258c0f8_1_182;
			++r28;
			if( r16 == NULL ) hl_null_access();
			r10 = hl_types_ArrayBytes_Float_pop(r16);
			goto label$258c0f8_1_176;
			label$258c0f8_1_182:
			goto label$258c0f8_1_153;
			label$258c0f8_1_183:
			r25 = r32->length;
			r28 = 0;
			if( r25 != r28 ) goto label$258c0f8_1_193;
			r21 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
			r25 = 0;
			r28 = 0;
			r10 = NULL;
			vision_ds_Array2D_new(r21,r25,r28,((vdynamic*)r10));
			r19 = r21;
			goto label$258c0f8_1_233;
			label$258c0f8_1_193:
			r21 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
			r25 = 0;
			r28 = r32->length;
			if( ((unsigned)r25) < ((unsigned)r28) ) goto label$258c0f8_1_199;
			r16 = NULL;
			goto label$258c0f8_1_202;
			label$258c0f8_1_199:
			r37 = r32->array;
			r8 = ((vdynamic**)(r37 + 1))[r25];
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			label$258c0f8_1_202:
			if( r16 == NULL ) hl_null_access();
			r25 = r16->length;
			r28 = r32->length;
			r10 = NULL;
			vision_ds_Array2D_new(r21,r25,r28,((vdynamic*)r10));
			r25 = 0;
			r15 = hl_alloc_bytes(r25);
			r25 = 0;
			r25 = 0;
			r16 = hl_types_ArrayBase_allocF64(r15,r25);
			r25 = 0;
			label$258c0f8_1_213:
			if( r32 == NULL ) hl_null_access();
			r34 = r32->length;
			if( r25 >= r34 ) goto label$258c0f8_1_229;
			r34 = r32->length;
			if( ((unsigned)r25) < ((unsigned)r34) ) goto label$258c0f8_1_221;
			r26 = NULL;
			goto label$258c0f8_1_224;
			label$258c0f8_1_221:
			r37 = r32->array;
			r8 = ((vdynamic**)(r37 + 1))[r25];
			r26 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			label$258c0f8_1_224:
			++r25;
			if( r16 == NULL ) hl_null_access();
			r39 = hl_types_ArrayBytes_Float_concat(r16,r26);
			r16 = r39;
			goto label$258c0f8_1_213;
			label$258c0f8_1_229:
			if( r21 == NULL ) hl_null_access();
			r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayDyn);
			r21->inner = r11;
			r19 = r21;
			label$258c0f8_1_233:
			r11 = r21->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r16 = hl_types_ArrayBytes_Float_copy(r16);
			r36 = (hl__types__ArrayObj)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayObj);
			r25 = 0;
			r28 = r21->height;
			label$258c0f8_1_240:
			if( r25 >= r28 ) goto label$258c0f8_1_256;
			r34 = r25;
			++r25;
			if( r36 == NULL ) hl_null_access();
			if( r19 == NULL ) hl_null_access();
			r42 = r19->width;
			r38 = r34 * r42;
			r35 = r24 + r38;
			r10 = NULL;
			r38 = r36->length;
			if( ((unsigned)r35) < ((unsigned)r38) ) goto label$258c0f8_1_253;
			hl_types_ArrayObj___expand(r36,r35);
			label$258c0f8_1_253:
			r37 = r36->array;
			((vdynamic**)(r37 + 1))[r35] = r10;
			goto label$258c0f8_1_240;
			label$258c0f8_1_256:
			r43 = &t$nul_f64;
			r25 = 0;
			r37 = hl_alloc_array(r43,r25);
			r41 = hl_types_ArrayObj_alloc(r37);
			r25 = 0;
			r44 = r36;
			label$258c0f8_1_262:
			if( r44 == NULL ) hl_null_access();
			r34 = r44->length;
			if( r25 >= r34 ) goto label$258c0f8_1_278;
			r34 = r44->length;
			if( ((unsigned)r25) < ((unsigned)r34) ) goto label$258c0f8_1_270;
			r10 = NULL;
			goto label$258c0f8_1_273;
			label$258c0f8_1_270:
			r37 = r44->array;
			r8 = ((vdynamic**)(r37 + 1))[r25];
			r10 = (vdynamic*)r8;
			label$258c0f8_1_273:
			++r25;
			if( !r10 ) goto label$258c0f8_1_277;
			if( r41 == NULL ) hl_null_access();
			r28 = hl_types_ArrayObj_push(r41,((vdynamic*)r10));
			label$258c0f8_1_277:
			goto label$258c0f8_1_262;
			label$258c0f8_1_278:
			if( r19 == NULL ) hl_null_access();
			r25 = r19->width;
			r28 = 1;
			r25 = r25 - r28;
			r11 = r19->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r34 = r19->height;
			r28 = r25 * r34;
			hl_types_ArrayBytes_Float_resize(r16,r28);
			r19->width = r25;
			r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r41,&t$hl_types_ArrayObj,&t$hl_types_ArrayDyn);
			r19->inner = r11;
			r46 = (double)r20;
			r46 = r46 * r29;
			r25 = r19->width;
			switch(r25) {
				default:
					r47 = 0.;
					r28 = 1;
					r34 = 0;
					r35 = r19->width;
					label$258c0f8_1_299:
					if( r34 >= r35 ) goto label$258c0f8_1_498;
					r38 = r34;
					++r34;
					if( r19 == NULL ) hl_null_access();
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r42 = 0;
					r48 = r19->width;
					r42 = r42 * r48;
					r42 = r42 + r38;
					r48 = r16->length;
					if( ((unsigned)r42) < ((unsigned)r48) ) goto label$258c0f8_1_315;
					r49 = 0.;
					goto label$258c0f8_1_319;
					label$258c0f8_1_315:
					r15 = r16->bytes;
					r48 = 3;
					r48 = r42 << r48;
					r49 = *(double*)(r15 + r48);
					label$258c0f8_1_319:
					r33 = NULL;
					r50 = NULL;
					r36 = vision_ds_Array2D_to2DArray(r19);
					if( r33 ) goto label$258c0f8_1_326;
					r42 = r19->width;
					r51 = hl_alloc_dynamic(&t$_i32);
					r51->v.i = r42;
					r33 = r51;
					label$258c0f8_1_326:
					if( r50 ) goto label$258c0f8_1_330;
					r42 = r19->height;
					r51 = hl_alloc_dynamic(&t$_i32);
					r51->v.i = r42;
					r50 = r51;
					label$258c0f8_1_330:
					r42 = 0;
					r48 = 1;
					label$258c0f8_1_332:
					if( r42 >= r48 ) goto label$258c0f8_1_339;
					++r42;
					if( r36 == NULL ) hl_null_access();
					r8 = hl_types_ArrayObj_shift(r36);
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					goto label$258c0f8_1_332;
					label$258c0f8_1_339:
					r42 = r33 ? r33->v.i : 0;
					if( r36 == NULL ) hl_null_access();
					r48 = r36->length;
					label$258c0f8_1_342:
					if( r42 >= r48 ) goto label$258c0f8_1_349;
					++r42;
					if( r36 == NULL ) hl_null_access();
					r8 = hl_types_ArrayObj_pop(r36);
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					goto label$258c0f8_1_342;
					label$258c0f8_1_349:
					r42 = 0;
					label$258c0f8_1_350:
					if( r36 == NULL ) hl_null_access();
					r52 = r36->length;
					if( r42 >= r52 ) goto label$258c0f8_1_380;
					r52 = r36->length;
					if( ((unsigned)r42) < ((unsigned)r52) ) goto label$258c0f8_1_358;
					r16 = NULL;
					goto label$258c0f8_1_361;
					label$258c0f8_1_358:
					r37 = r36->array;
					r8 = ((vdynamic**)(r37 + 1))[r42];
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					label$258c0f8_1_361:
					++r42;
					r48 = 0;
					r52 = 0;
					label$258c0f8_1_364:
					if( r48 >= r52 ) goto label$258c0f8_1_370;
					++r48;
					if( r16 == NULL ) hl_null_access();
					r10 = hl_types_ArrayBytes_Float_shift(r16);
					goto label$258c0f8_1_364;
					label$258c0f8_1_370:
					r48 = r50 ? r50->v.i : 0;
					if( r16 == NULL ) hl_null_access();
					r52 = r16->length;
					label$258c0f8_1_373:
					if( r48 >= r52 ) goto label$258c0f8_1_379;
					++r48;
					if( r16 == NULL ) hl_null_access();
					r10 = hl_types_ArrayBytes_Float_pop(r16);
					goto label$258c0f8_1_373;
					label$258c0f8_1_379:
					goto label$258c0f8_1_350;
					label$258c0f8_1_380:
					r42 = r36->length;
					r48 = 0;
					if( r42 != r48 ) goto label$258c0f8_1_390;
					r40 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
					r42 = 0;
					r48 = 0;
					r10 = NULL;
					vision_ds_Array2D_new(r40,r42,r48,((vdynamic*)r10));
					r21 = r40;
					goto label$258c0f8_1_430;
					label$258c0f8_1_390:
					r40 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
					r42 = 0;
					r48 = r36->length;
					if( ((unsigned)r42) < ((unsigned)r48) ) goto label$258c0f8_1_396;
					r16 = NULL;
					goto label$258c0f8_1_399;
					label$258c0f8_1_396:
					r37 = r36->array;
					r8 = ((vdynamic**)(r37 + 1))[r42];
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					label$258c0f8_1_399:
					if( r16 == NULL ) hl_null_access();
					r42 = r16->length;
					r48 = r36->length;
					r10 = NULL;
					vision_ds_Array2D_new(r40,r42,r48,((vdynamic*)r10));
					r42 = 0;
					r15 = hl_alloc_bytes(r42);
					r42 = 0;
					r42 = 0;
					r16 = hl_types_ArrayBase_allocF64(r15,r42);
					r42 = 0;
					label$258c0f8_1_410:
					if( r36 == NULL ) hl_null_access();
					r52 = r36->length;
					if( r42 >= r52 ) goto label$258c0f8_1_426;
					r52 = r36->length;
					if( ((unsigned)r42) < ((unsigned)r52) ) goto label$258c0f8_1_418;
					r26 = NULL;
					goto label$258c0f8_1_421;
					label$258c0f8_1_418:
					r37 = r36->array;
					r8 = ((vdynamic**)(r37 + 1))[r42];
					r26 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					label$258c0f8_1_421:
					++r42;
					if( r16 == NULL ) hl_null_access();
					r39 = hl_types_ArrayBytes_Float_concat(r16,r26);
					r16 = r39;
					goto label$258c0f8_1_410;
					label$258c0f8_1_426:
					if( r40 == NULL ) hl_null_access();
					r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayDyn);
					r40->inner = r11;
					r21 = r40;
					label$258c0f8_1_430:
					r11 = r40->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r16 = hl_types_ArrayBytes_Float_copy(r16);
					r41 = (hl__types__ArrayObj)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayObj);
					r42 = 0;
					r48 = r40->height;
					label$258c0f8_1_437:
					if( r42 >= r48 ) goto label$258c0f8_1_453;
					r52 = r42;
					++r42;
					if( r41 == NULL ) hl_null_access();
					if( r21 == NULL ) hl_null_access();
					r55 = r21->width;
					r54 = r52 * r55;
					r53 = r38 + r54;
					r10 = NULL;
					r54 = r41->length;
					if( ((unsigned)r53) < ((unsigned)r54) ) goto label$258c0f8_1_450;
					hl_types_ArrayObj___expand(r41,r53);
					label$258c0f8_1_450:
					r37 = r41->array;
					((vdynamic**)(r37 + 1))[r53] = r10;
					goto label$258c0f8_1_437;
					label$258c0f8_1_453:
					r43 = &t$nul_f64;
					r42 = 0;
					r37 = hl_alloc_array(r43,r42);
					r44 = hl_types_ArrayObj_alloc(r37);
					r42 = 0;
					r45 = r41;
					label$258c0f8_1_459:
					if( r45 == NULL ) hl_null_access();
					r52 = r45->length;
					if( r42 >= r52 ) goto label$258c0f8_1_475;
					r52 = r45->length;
					if( ((unsigned)r42) < ((unsigned)r52) ) goto label$258c0f8_1_467;
					r10 = NULL;
					goto label$258c0f8_1_470;
					label$258c0f8_1_467:
					r37 = r45->array;
					r8 = ((vdynamic**)(r37 + 1))[r42];
					r10 = (vdynamic*)r8;
					label$258c0f8_1_470:
					++r42;
					if( !r10 ) goto label$258c0f8_1_474;
					if( r44 == NULL ) hl_null_access();
					r48 = hl_types_ArrayObj_push(r44,((vdynamic*)r10));
					label$258c0f8_1_474:
					goto label$258c0f8_1_459;
					label$258c0f8_1_475:
					if( r21 == NULL ) hl_null_access();
					r42 = r21->width;
					r48 = 1;
					r42 = r42 - r48;
					r11 = r21->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r52 = r21->height;
					r48 = r42 * r52;
					hl_types_ArrayBytes_Float_resize(r16,r48);
					r21->width = r42;
					r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r44,&t$hl_types_ArrayObj,&t$hl_types_ArrayDyn);
					r21->inner = r11;
					r57 = (double)r28;
					r57 = r57 * r49;
					r58 = vision_ds__Matrix2D_Matrix2D_Impl__getDeterminant(r21);
					r57 = r57 * r58;
					r56 = r47 + r57;
					r47 = r56;
					r48 = -1;
					r42 = r28 * r48;
					r28 = r42;
					goto label$258c0f8_1_299;
					label$258c0f8_1_498:
					r49 = r47;
					goto label$258c0f8_1_579;
				case 0:
					r47 = 1.;
					r49 = r47;
					goto label$258c0f8_1_579;
				case 1:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r28 = 0;
					r34 = r19->width;
					r28 = r28 * r34;
					r34 = r16->length;
					if( ((unsigned)r28) < ((unsigned)r34) ) goto label$258c0f8_1_513;
					r47 = 0.;
					goto label$258c0f8_1_517;
					label$258c0f8_1_513:
					r15 = r16->bytes;
					r34 = 3;
					r34 = r28 << r34;
					r47 = *(double*)(r15 + r34);
					label$258c0f8_1_517:
					r49 = r47;
					goto label$258c0f8_1_579;
				case 2:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r28 = 0;
					r34 = r19->width;
					r28 = r28 * r34;
					r34 = r16->length;
					if( ((unsigned)r28) < ((unsigned)r34) ) goto label$258c0f8_1_529;
					r47 = 0.;
					goto label$258c0f8_1_533;
					label$258c0f8_1_529:
					r15 = r16->bytes;
					r34 = 3;
					r34 = r28 << r34;
					r47 = *(double*)(r15 + r34);
					label$258c0f8_1_533:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r28 = r19->width;
					r34 = 1;
					r28 = r28 + r34;
					r34 = r16->length;
					if( ((unsigned)r28) < ((unsigned)r34) ) goto label$258c0f8_1_543;
					r56 = 0.;
					goto label$258c0f8_1_547;
					label$258c0f8_1_543:
					r15 = r16->bytes;
					r34 = 3;
					r34 = r28 << r34;
					r56 = *(double*)(r15 + r34);
					label$258c0f8_1_547:
					r47 = r47 * r56;
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r28 = r19->width;
					r34 = r16->length;
					if( ((unsigned)r28) < ((unsigned)r34) ) goto label$258c0f8_1_556;
					r56 = 0.;
					goto label$258c0f8_1_560;
					label$258c0f8_1_556:
					r15 = r16->bytes;
					r34 = 3;
					r34 = r28 << r34;
					r56 = *(double*)(r15 + r34);
					label$258c0f8_1_560:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r28 = 0;
					r34 = r19->width;
					r28 = r28 * r34;
					r34 = 1;
					r28 = r28 + r34;
					r34 = r16->length;
					if( ((unsigned)r28) < ((unsigned)r34) ) goto label$258c0f8_1_572;
					r57 = 0.;
					goto label$258c0f8_1_576;
					label$258c0f8_1_572:
					r15 = r16->bytes;
					r34 = 3;
					r34 = r28 << r34;
					r57 = *(double*)(r15 + r34);
					label$258c0f8_1_576:
					r56 = r56 * r57;
					r47 = r47 - r56;
					r49 = r47;
			}
			label$258c0f8_1_579:
			r56 = r46 * r49;
			r47 = r27 + r56;
			r27 = r47;
			r34 = -1;
			r28 = r20 * r34;
			r20 = r28;
			goto label$258c0f8_1_102;
			label$258c0f8_1_586:
			r29 = r27;
			goto label$258c0f8_1_667;
		case 0:
			r27 = 1.;
			r29 = r27;
			goto label$258c0f8_1_667;
		case 1:
			r11 = r13->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r20 = 0;
			r22 = r13->width;
			r20 = r20 * r22;
			r22 = r16->length;
			if( ((unsigned)r20) < ((unsigned)r22) ) goto label$258c0f8_1_601;
			r27 = 0.;
			goto label$258c0f8_1_605;
			label$258c0f8_1_601:
			r15 = r16->bytes;
			r22 = 3;
			r22 = r20 << r22;
			r27 = *(double*)(r15 + r22);
			label$258c0f8_1_605:
			r29 = r27;
			goto label$258c0f8_1_667;
		case 2:
			r11 = r13->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r20 = 0;
			r22 = r13->width;
			r20 = r20 * r22;
			r22 = r16->length;
			if( ((unsigned)r20) < ((unsigned)r22) ) goto label$258c0f8_1_617;
			r27 = 0.;
			goto label$258c0f8_1_621;
			label$258c0f8_1_617:
			r15 = r16->bytes;
			r22 = 3;
			r22 = r20 << r22;
			r27 = *(double*)(r15 + r22);
			label$258c0f8_1_621:
			r11 = r13->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r20 = r13->width;
			r22 = 1;
			r20 = r20 + r22;
			r22 = r16->length;
			if( ((unsigned)r20) < ((unsigned)r22) ) goto label$258c0f8_1_631;
			r46 = 0.;
			goto label$258c0f8_1_635;
			label$258c0f8_1_631:
			r15 = r16->bytes;
			r22 = 3;
			r22 = r20 << r22;
			r46 = *(double*)(r15 + r22);
			label$258c0f8_1_635:
			r27 = r27 * r46;
			r11 = r13->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r20 = r13->width;
			r22 = r16->length;
			if( ((unsigned)r20) < ((unsigned)r22) ) goto label$258c0f8_1_644;
			r46 = 0.;
			goto label$258c0f8_1_648;
			label$258c0f8_1_644:
			r15 = r16->bytes;
			r22 = 3;
			r22 = r20 << r22;
			r46 = *(double*)(r15 + r22);
			label$258c0f8_1_648:
			r11 = r13->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r20 = 0;
			r22 = r13->width;
			r20 = r20 * r22;
			r22 = 1;
			r20 = r20 + r22;
			r22 = r16->length;
			if( ((unsigned)r20) < ((unsigned)r22) ) goto label$258c0f8_1_660;
			r47 = 0.;
			goto label$258c0f8_1_664;
			label$258c0f8_1_660:
			r15 = r16->bytes;
			r22 = 3;
			r22 = r20 << r22;
			r47 = *(double*)(r15 + r22);
			label$258c0f8_1_664:
			r46 = r46 * r47;
			r27 = r27 - r46;
			r29 = r27;
	}
	label$258c0f8_1_667:
	if( r9 == NULL ) hl_null_access();
	r20 = r9->width;
	switch(r20) {
		default:
			r27 = 0.;
			r22 = 1;
			r23 = 0;
			r24 = r9->width;
			label$258c0f8_1_674:
			if( r23 >= r24 ) goto label$258c0f8_1_1158;
			r25 = r23;
			++r23;
			if( r9 == NULL ) hl_null_access();
			r11 = r9->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r28 = 0;
			r34 = r9->width;
			r28 = r28 * r34;
			r28 = r28 + r25;
			r34 = r16->length;
			if( ((unsigned)r28) < ((unsigned)r34) ) goto label$258c0f8_1_690;
			r46 = 0.;
			goto label$258c0f8_1_694;
			label$258c0f8_1_690:
			r15 = r16->bytes;
			r34 = 3;
			r34 = r28 << r34;
			r46 = *(double*)(r15 + r34);
			label$258c0f8_1_694:
			r30 = NULL;
			r31 = NULL;
			r32 = vision_ds_Array2D_to2DArray(r9);
			if( r30 ) goto label$258c0f8_1_701;
			r28 = r9->width;
			r33 = hl_alloc_dynamic(&t$_i32);
			r33->v.i = r28;
			r30 = r33;
			label$258c0f8_1_701:
			if( r31 ) goto label$258c0f8_1_705;
			r28 = r9->height;
			r33 = hl_alloc_dynamic(&t$_i32);
			r33->v.i = r28;
			r31 = r33;
			label$258c0f8_1_705:
			r28 = 0;
			r34 = 1;
			label$258c0f8_1_707:
			if( r28 >= r34 ) goto label$258c0f8_1_714;
			++r28;
			if( r32 == NULL ) hl_null_access();
			r8 = hl_types_ArrayObj_shift(r32);
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			goto label$258c0f8_1_707;
			label$258c0f8_1_714:
			r28 = r30 ? r30->v.i : 0;
			if( r32 == NULL ) hl_null_access();
			r34 = r32->length;
			label$258c0f8_1_717:
			if( r28 >= r34 ) goto label$258c0f8_1_724;
			++r28;
			if( r32 == NULL ) hl_null_access();
			r8 = hl_types_ArrayObj_pop(r32);
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			goto label$258c0f8_1_717;
			label$258c0f8_1_724:
			r28 = 0;
			label$258c0f8_1_725:
			if( r32 == NULL ) hl_null_access();
			r35 = r32->length;
			if( r28 >= r35 ) goto label$258c0f8_1_755;
			r35 = r32->length;
			if( ((unsigned)r28) < ((unsigned)r35) ) goto label$258c0f8_1_733;
			r16 = NULL;
			goto label$258c0f8_1_736;
			label$258c0f8_1_733:
			r37 = r32->array;
			r8 = ((vdynamic**)(r37 + 1))[r28];
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			label$258c0f8_1_736:
			++r28;
			r34 = 0;
			r35 = 0;
			label$258c0f8_1_739:
			if( r34 >= r35 ) goto label$258c0f8_1_745;
			++r34;
			if( r16 == NULL ) hl_null_access();
			r10 = hl_types_ArrayBytes_Float_shift(r16);
			goto label$258c0f8_1_739;
			label$258c0f8_1_745:
			r34 = r31 ? r31->v.i : 0;
			if( r16 == NULL ) hl_null_access();
			r35 = r16->length;
			label$258c0f8_1_748:
			if( r34 >= r35 ) goto label$258c0f8_1_754;
			++r34;
			if( r16 == NULL ) hl_null_access();
			r10 = hl_types_ArrayBytes_Float_pop(r16);
			goto label$258c0f8_1_748;
			label$258c0f8_1_754:
			goto label$258c0f8_1_725;
			label$258c0f8_1_755:
			r28 = r32->length;
			r34 = 0;
			if( r28 != r34 ) goto label$258c0f8_1_765;
			r21 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
			r28 = 0;
			r34 = 0;
			r10 = NULL;
			vision_ds_Array2D_new(r21,r28,r34,((vdynamic*)r10));
			r19 = r21;
			goto label$258c0f8_1_805;
			label$258c0f8_1_765:
			r21 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
			r28 = 0;
			r34 = r32->length;
			if( ((unsigned)r28) < ((unsigned)r34) ) goto label$258c0f8_1_771;
			r16 = NULL;
			goto label$258c0f8_1_774;
			label$258c0f8_1_771:
			r37 = r32->array;
			r8 = ((vdynamic**)(r37 + 1))[r28];
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			label$258c0f8_1_774:
			if( r16 == NULL ) hl_null_access();
			r28 = r16->length;
			r34 = r32->length;
			r10 = NULL;
			vision_ds_Array2D_new(r21,r28,r34,((vdynamic*)r10));
			r28 = 0;
			r15 = hl_alloc_bytes(r28);
			r28 = 0;
			r28 = 0;
			r16 = hl_types_ArrayBase_allocF64(r15,r28);
			r28 = 0;
			label$258c0f8_1_785:
			if( r32 == NULL ) hl_null_access();
			r35 = r32->length;
			if( r28 >= r35 ) goto label$258c0f8_1_801;
			r35 = r32->length;
			if( ((unsigned)r28) < ((unsigned)r35) ) goto label$258c0f8_1_793;
			r26 = NULL;
			goto label$258c0f8_1_796;
			label$258c0f8_1_793:
			r37 = r32->array;
			r8 = ((vdynamic**)(r37 + 1))[r28];
			r26 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
			label$258c0f8_1_796:
			++r28;
			if( r16 == NULL ) hl_null_access();
			r39 = hl_types_ArrayBytes_Float_concat(r16,r26);
			r16 = r39;
			goto label$258c0f8_1_785;
			label$258c0f8_1_801:
			if( r21 == NULL ) hl_null_access();
			r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayDyn);
			r21->inner = r11;
			r19 = r21;
			label$258c0f8_1_805:
			r11 = r21->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r16 = hl_types_ArrayBytes_Float_copy(r16);
			r36 = (hl__types__ArrayObj)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayObj);
			r28 = 0;
			r34 = r21->height;
			label$258c0f8_1_812:
			if( r28 >= r34 ) goto label$258c0f8_1_828;
			r35 = r28;
			++r28;
			if( r36 == NULL ) hl_null_access();
			if( r19 == NULL ) hl_null_access();
			r48 = r19->width;
			r42 = r35 * r48;
			r38 = r25 + r42;
			r10 = NULL;
			r42 = r36->length;
			if( ((unsigned)r38) < ((unsigned)r42) ) goto label$258c0f8_1_825;
			hl_types_ArrayObj___expand(r36,r38);
			label$258c0f8_1_825:
			r37 = r36->array;
			((vdynamic**)(r37 + 1))[r38] = r10;
			goto label$258c0f8_1_812;
			label$258c0f8_1_828:
			r43 = &t$nul_f64;
			r28 = 0;
			r37 = hl_alloc_array(r43,r28);
			r41 = hl_types_ArrayObj_alloc(r37);
			r28 = 0;
			r44 = r36;
			label$258c0f8_1_834:
			if( r44 == NULL ) hl_null_access();
			r35 = r44->length;
			if( r28 >= r35 ) goto label$258c0f8_1_850;
			r35 = r44->length;
			if( ((unsigned)r28) < ((unsigned)r35) ) goto label$258c0f8_1_842;
			r10 = NULL;
			goto label$258c0f8_1_845;
			label$258c0f8_1_842:
			r37 = r44->array;
			r8 = ((vdynamic**)(r37 + 1))[r28];
			r10 = (vdynamic*)r8;
			label$258c0f8_1_845:
			++r28;
			if( !r10 ) goto label$258c0f8_1_849;
			if( r41 == NULL ) hl_null_access();
			r34 = hl_types_ArrayObj_push(r41,((vdynamic*)r10));
			label$258c0f8_1_849:
			goto label$258c0f8_1_834;
			label$258c0f8_1_850:
			if( r19 == NULL ) hl_null_access();
			r28 = r19->width;
			r34 = 1;
			r28 = r28 - r34;
			r11 = r19->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r35 = r19->height;
			r34 = r28 * r35;
			hl_types_ArrayBytes_Float_resize(r16,r34);
			r19->width = r28;
			r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r41,&t$hl_types_ArrayObj,&t$hl_types_ArrayDyn);
			r19->inner = r11;
			r47 = (double)r22;
			r47 = r47 * r46;
			r28 = r19->width;
			switch(r28) {
				default:
					r49 = 0.;
					r34 = 1;
					r35 = 0;
					r38 = r19->width;
					label$258c0f8_1_871:
					if( r35 >= r38 ) goto label$258c0f8_1_1070;
					r42 = r35;
					++r35;
					if( r19 == NULL ) hl_null_access();
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r48 = 0;
					r52 = r19->width;
					r48 = r48 * r52;
					r48 = r48 + r42;
					r52 = r16->length;
					if( ((unsigned)r48) < ((unsigned)r52) ) goto label$258c0f8_1_887;
					r56 = 0.;
					goto label$258c0f8_1_891;
					label$258c0f8_1_887:
					r15 = r16->bytes;
					r52 = 3;
					r52 = r48 << r52;
					r56 = *(double*)(r15 + r52);
					label$258c0f8_1_891:
					r33 = NULL;
					r50 = NULL;
					r36 = vision_ds_Array2D_to2DArray(r19);
					if( r33 ) goto label$258c0f8_1_898;
					r48 = r19->width;
					r51 = hl_alloc_dynamic(&t$_i32);
					r51->v.i = r48;
					r33 = r51;
					label$258c0f8_1_898:
					if( r50 ) goto label$258c0f8_1_902;
					r48 = r19->height;
					r51 = hl_alloc_dynamic(&t$_i32);
					r51->v.i = r48;
					r50 = r51;
					label$258c0f8_1_902:
					r48 = 0;
					r52 = 1;
					label$258c0f8_1_904:
					if( r48 >= r52 ) goto label$258c0f8_1_911;
					++r48;
					if( r36 == NULL ) hl_null_access();
					r8 = hl_types_ArrayObj_shift(r36);
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					goto label$258c0f8_1_904;
					label$258c0f8_1_911:
					r48 = r33 ? r33->v.i : 0;
					if( r36 == NULL ) hl_null_access();
					r52 = r36->length;
					label$258c0f8_1_914:
					if( r48 >= r52 ) goto label$258c0f8_1_921;
					++r48;
					if( r36 == NULL ) hl_null_access();
					r8 = hl_types_ArrayObj_pop(r36);
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					goto label$258c0f8_1_914;
					label$258c0f8_1_921:
					r48 = 0;
					label$258c0f8_1_922:
					if( r36 == NULL ) hl_null_access();
					r53 = r36->length;
					if( r48 >= r53 ) goto label$258c0f8_1_952;
					r53 = r36->length;
					if( ((unsigned)r48) < ((unsigned)r53) ) goto label$258c0f8_1_930;
					r16 = NULL;
					goto label$258c0f8_1_933;
					label$258c0f8_1_930:
					r37 = r36->array;
					r8 = ((vdynamic**)(r37 + 1))[r48];
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					label$258c0f8_1_933:
					++r48;
					r52 = 0;
					r53 = 0;
					label$258c0f8_1_936:
					if( r52 >= r53 ) goto label$258c0f8_1_942;
					++r52;
					if( r16 == NULL ) hl_null_access();
					r10 = hl_types_ArrayBytes_Float_shift(r16);
					goto label$258c0f8_1_936;
					label$258c0f8_1_942:
					r52 = r50 ? r50->v.i : 0;
					if( r16 == NULL ) hl_null_access();
					r53 = r16->length;
					label$258c0f8_1_945:
					if( r52 >= r53 ) goto label$258c0f8_1_951;
					++r52;
					if( r16 == NULL ) hl_null_access();
					r10 = hl_types_ArrayBytes_Float_pop(r16);
					goto label$258c0f8_1_945;
					label$258c0f8_1_951:
					goto label$258c0f8_1_922;
					label$258c0f8_1_952:
					r48 = r36->length;
					r52 = 0;
					if( r48 != r52 ) goto label$258c0f8_1_962;
					r40 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
					r48 = 0;
					r52 = 0;
					r10 = NULL;
					vision_ds_Array2D_new(r40,r48,r52,((vdynamic*)r10));
					r21 = r40;
					goto label$258c0f8_1_1002;
					label$258c0f8_1_962:
					r40 = (vision__ds__Array2D)hl_alloc_obj(&t$vision_ds_Array2D);
					r48 = 0;
					r52 = r36->length;
					if( ((unsigned)r48) < ((unsigned)r52) ) goto label$258c0f8_1_968;
					r16 = NULL;
					goto label$258c0f8_1_971;
					label$258c0f8_1_968:
					r37 = r36->array;
					r8 = ((vdynamic**)(r37 + 1))[r48];
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					label$258c0f8_1_971:
					if( r16 == NULL ) hl_null_access();
					r48 = r16->length;
					r52 = r36->length;
					r10 = NULL;
					vision_ds_Array2D_new(r40,r48,r52,((vdynamic*)r10));
					r48 = 0;
					r15 = hl_alloc_bytes(r48);
					r48 = 0;
					r48 = 0;
					r16 = hl_types_ArrayBase_allocF64(r15,r48);
					r48 = 0;
					label$258c0f8_1_982:
					if( r36 == NULL ) hl_null_access();
					r53 = r36->length;
					if( r48 >= r53 ) goto label$258c0f8_1_998;
					r53 = r36->length;
					if( ((unsigned)r48) < ((unsigned)r53) ) goto label$258c0f8_1_990;
					r26 = NULL;
					goto label$258c0f8_1_993;
					label$258c0f8_1_990:
					r37 = r36->array;
					r8 = ((vdynamic**)(r37 + 1))[r48];
					r26 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r8,&t$_dyn,&t$hl_types_ArrayBytes_Float);
					label$258c0f8_1_993:
					++r48;
					if( r16 == NULL ) hl_null_access();
					r39 = hl_types_ArrayBytes_Float_concat(r16,r26);
					r16 = r39;
					goto label$258c0f8_1_982;
					label$258c0f8_1_998:
					if( r40 == NULL ) hl_null_access();
					r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayDyn);
					r40->inner = r11;
					r21 = r40;
					label$258c0f8_1_1002:
					r11 = r40->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r16 = hl_types_ArrayBytes_Float_copy(r16);
					r41 = (hl__types__ArrayObj)hl_dyn_castp(&r16,&t$hl_types_ArrayBytes_Float,&t$hl_types_ArrayObj);
					r48 = 0;
					r52 = r40->height;
					label$258c0f8_1_1009:
					if( r48 >= r52 ) goto label$258c0f8_1_1025;
					r53 = r48;
					++r48;
					if( r41 == NULL ) hl_null_access();
					if( r21 == NULL ) hl_null_access();
					r59 = r21->width;
					r55 = r53 * r59;
					r54 = r42 + r55;
					r10 = NULL;
					r55 = r41->length;
					if( ((unsigned)r54) < ((unsigned)r55) ) goto label$258c0f8_1_1022;
					hl_types_ArrayObj___expand(r41,r54);
					label$258c0f8_1_1022:
					r37 = r41->array;
					((vdynamic**)(r37 + 1))[r54] = r10;
					goto label$258c0f8_1_1009;
					label$258c0f8_1_1025:
					r43 = &t$nul_f64;
					r48 = 0;
					r37 = hl_alloc_array(r43,r48);
					r44 = hl_types_ArrayObj_alloc(r37);
					r48 = 0;
					r45 = r41;
					label$258c0f8_1_1031:
					if( r45 == NULL ) hl_null_access();
					r53 = r45->length;
					if( r48 >= r53 ) goto label$258c0f8_1_1047;
					r53 = r45->length;
					if( ((unsigned)r48) < ((unsigned)r53) ) goto label$258c0f8_1_1039;
					r10 = NULL;
					goto label$258c0f8_1_1042;
					label$258c0f8_1_1039:
					r37 = r45->array;
					r8 = ((vdynamic**)(r37 + 1))[r48];
					r10 = (vdynamic*)r8;
					label$258c0f8_1_1042:
					++r48;
					if( !r10 ) goto label$258c0f8_1_1046;
					if( r44 == NULL ) hl_null_access();
					r52 = hl_types_ArrayObj_push(r44,((vdynamic*)r10));
					label$258c0f8_1_1046:
					goto label$258c0f8_1_1031;
					label$258c0f8_1_1047:
					if( r21 == NULL ) hl_null_access();
					r48 = r21->width;
					r52 = 1;
					r48 = r48 - r52;
					r11 = r21->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r53 = r21->height;
					r52 = r48 * r53;
					hl_types_ArrayBytes_Float_resize(r16,r52);
					r21->width = r48;
					r11 = (hl__types__ArrayDyn)hl_dyn_castp(&r44,&t$hl_types_ArrayObj,&t$hl_types_ArrayDyn);
					r21->inner = r11;
					r58 = (double)r34;
					r58 = r58 * r56;
					r60 = vision_ds__Matrix2D_Matrix2D_Impl__getDeterminant(r21);
					r58 = r58 * r60;
					r57 = r49 + r58;
					r49 = r57;
					r52 = -1;
					r48 = r34 * r52;
					r34 = r48;
					goto label$258c0f8_1_871;
					label$258c0f8_1_1070:
					r56 = r49;
					goto label$258c0f8_1_1151;
				case 0:
					r49 = 1.;
					r56 = r49;
					goto label$258c0f8_1_1151;
				case 1:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r34 = 0;
					r35 = r19->width;
					r34 = r34 * r35;
					r35 = r16->length;
					if( ((unsigned)r34) < ((unsigned)r35) ) goto label$258c0f8_1_1085;
					r49 = 0.;
					goto label$258c0f8_1_1089;
					label$258c0f8_1_1085:
					r15 = r16->bytes;
					r35 = 3;
					r35 = r34 << r35;
					r49 = *(double*)(r15 + r35);
					label$258c0f8_1_1089:
					r56 = r49;
					goto label$258c0f8_1_1151;
				case 2:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r34 = 0;
					r35 = r19->width;
					r34 = r34 * r35;
					r35 = r16->length;
					if( ((unsigned)r34) < ((unsigned)r35) ) goto label$258c0f8_1_1101;
					r49 = 0.;
					goto label$258c0f8_1_1105;
					label$258c0f8_1_1101:
					r15 = r16->bytes;
					r35 = 3;
					r35 = r34 << r35;
					r49 = *(double*)(r15 + r35);
					label$258c0f8_1_1105:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r34 = r19->width;
					r35 = 1;
					r34 = r34 + r35;
					r35 = r16->length;
					if( ((unsigned)r34) < ((unsigned)r35) ) goto label$258c0f8_1_1115;
					r57 = 0.;
					goto label$258c0f8_1_1119;
					label$258c0f8_1_1115:
					r15 = r16->bytes;
					r35 = 3;
					r35 = r34 << r35;
					r57 = *(double*)(r15 + r35);
					label$258c0f8_1_1119:
					r49 = r49 * r57;
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r34 = r19->width;
					r35 = r16->length;
					if( ((unsigned)r34) < ((unsigned)r35) ) goto label$258c0f8_1_1128;
					r57 = 0.;
					goto label$258c0f8_1_1132;
					label$258c0f8_1_1128:
					r15 = r16->bytes;
					r35 = 3;
					r35 = r34 << r35;
					r57 = *(double*)(r15 + r35);
					label$258c0f8_1_1132:
					r11 = r19->inner;
					r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
					if( r16 == NULL ) hl_null_access();
					r34 = 0;
					r35 = r19->width;
					r34 = r34 * r35;
					r35 = 1;
					r34 = r34 + r35;
					r35 = r16->length;
					if( ((unsigned)r34) < ((unsigned)r35) ) goto label$258c0f8_1_1144;
					r58 = 0.;
					goto label$258c0f8_1_1148;
					label$258c0f8_1_1144:
					r15 = r16->bytes;
					r35 = 3;
					r35 = r34 << r35;
					r58 = *(double*)(r15 + r35);
					label$258c0f8_1_1148:
					r57 = r57 * r58;
					r49 = r49 - r57;
					r56 = r49;
			}
			label$258c0f8_1_1151:
			r57 = r47 * r56;
			r49 = r27 + r57;
			r27 = r49;
			r35 = -1;
			r34 = r22 * r35;
			r22 = r34;
			goto label$258c0f8_1_674;
			label$258c0f8_1_1158:
			r46 = r27;
			goto label$258c0f8_1_1239;
		case 0:
			r27 = 1.;
			r46 = r27;
			goto label$258c0f8_1_1239;
		case 1:
			r11 = r9->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r22 = 0;
			r23 = r9->width;
			r22 = r22 * r23;
			r23 = r16->length;
			if( ((unsigned)r22) < ((unsigned)r23) ) goto label$258c0f8_1_1173;
			r27 = 0.;
			goto label$258c0f8_1_1177;
			label$258c0f8_1_1173:
			r15 = r16->bytes;
			r23 = 3;
			r23 = r22 << r23;
			r27 = *(double*)(r15 + r23);
			label$258c0f8_1_1177:
			r46 = r27;
			goto label$258c0f8_1_1239;
		case 2:
			r11 = r9->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r22 = 0;
			r23 = r9->width;
			r22 = r22 * r23;
			r23 = r16->length;
			if( ((unsigned)r22) < ((unsigned)r23) ) goto label$258c0f8_1_1189;
			r27 = 0.;
			goto label$258c0f8_1_1193;
			label$258c0f8_1_1189:
			r15 = r16->bytes;
			r23 = 3;
			r23 = r22 << r23;
			r27 = *(double*)(r15 + r23);
			label$258c0f8_1_1193:
			r11 = r9->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r22 = r9->width;
			r23 = 1;
			r22 = r22 + r23;
			r23 = r16->length;
			if( ((unsigned)r22) < ((unsigned)r23) ) goto label$258c0f8_1_1203;
			r47 = 0.;
			goto label$258c0f8_1_1207;
			label$258c0f8_1_1203:
			r15 = r16->bytes;
			r23 = 3;
			r23 = r22 << r23;
			r47 = *(double*)(r15 + r23);
			label$258c0f8_1_1207:
			r27 = r27 * r47;
			r11 = r9->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r22 = r9->width;
			r23 = r16->length;
			if( ((unsigned)r22) < ((unsigned)r23) ) goto label$258c0f8_1_1216;
			r47 = 0.;
			goto label$258c0f8_1_1220;
			label$258c0f8_1_1216:
			r15 = r16->bytes;
			r23 = 3;
			r23 = r22 << r23;
			r47 = *(double*)(r15 + r23);
			label$258c0f8_1_1220:
			r11 = r9->inner;
			r16 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r11,&t$hl_types_ArrayDyn,&t$hl_types_ArrayBytes_Float);
			if( r16 == NULL ) hl_null_access();
			r22 = 0;
			r23 = r9->width;
			r22 = r22 * r23;
			r23 = 1;
			r22 = r22 + r23;
			r23 = r16->length;
			if( ((unsigned)r22) < ((unsigned)r23) ) goto label$258c0f8_1_1232;
			r49 = 0.;
			goto label$258c0f8_1_1236;
			label$258c0f8_1_1232:
			r15 = r16->bytes;
			r23 = 3;
			r23 = r22 << r23;
			r49 = *(double*)(r15 + r23);
			label$258c0f8_1_1236:
			r47 = r47 * r49;
			r27 = r27 - r47;
			r46 = r27;
	}
	label$258c0f8_1_1239:
	if( r6 == NULL ) hl_null_access();
	r27 = r29 / r46;
	r22 = hl_types_ArrayBytes_Float_push(r6,r27);
	goto label$258c0f8_1_42;
	label$258c0f8_1_1243:
	return r6;
}

