// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__ds__Array2D
#define INC_vision__ds__Array2D
typedef struct _vision__ds__$Array2D *vision__ds__$Array2D;
typedef struct _vision__ds__Array2D *vision__ds__Array2D;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayDyn.h>


struct _vision__ds__$Array2D {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _vision__ds__Array2D {
	hl_type *$type;
	hl__types__ArrayDyn inner;
	int width;
	int height;
};
#endif

