// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__ds__Queue
#define INC_vision__ds__Queue
typedef struct _vision__ds__$Queue *vision__ds__$Queue;
typedef struct _vision__ds__Queue *vision__ds__Queue;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <vision/ds/QueueCell.h>


struct _vision__ds__$Queue {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _vision__ds__Queue {
	hl_type *$type;
	int length;
	vision__ds__QueueCell first;
};
#endif

