// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <vision/ds/QueueCell.h>

void vision_ds_QueueCell_new(vision__ds__QueueCell r0,vdynamic* r1,vision__ds__QueueCell r2,vision__ds__QueueCell r3) {
	r0->previous = r3;
	r0->value = r1;
	r0->next = r2;
	return;
}

