// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/_CallStack/CallStack_Impl_.h>
extern hl_type t$StringBuf;
void StringBuf_new(StringBuf);
extern String s$_Called_from_;
void StringBuf_add(StringBuf,vdynamic*);
void haxe__CallStack_CallStack_Impl__itemToString(StringBuf,venum*);
String StringBuf_toString(StringBuf);
#include <hl/types/ArrayBase.h>
bool haxe__CallStack_CallStack_Impl__equalItems(venum*,venum*);
extern hl_type t$_i32;
hl__types__ArrayBase hl_types_ArrayObj_slice(hl__types__ArrayObj,int,vdynamic*);
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$hl_types_ArrayBase;
int String___compare(String,vdynamic*);
extern String s$a_C_function;
extern String s$module_;
extern String s$bbee82c;
extern String s$_line_;
extern String s$_column_;
extern String s$9371d7a;
extern String s$2f6bac6;
extern String s$5058f1a;
extern String s$local_function_;

String haxe__CallStack_CallStack_Impl__toString(hl__types__ArrayObj r0) {
	String r9;
	hl__types__ArrayObj r4;
	venum *r6;
	StringBuf r1;
	vdynamic *r7;
	varray *r8;
	int r3, r5;
	r1 = (StringBuf)hl_alloc_obj(&t$StringBuf);
	StringBuf_new(r1);
	r3 = 0;
	r4 = r0;
	label$e26c8ce_1_4:
	if( r4 == NULL ) hl_null_access();
	r5 = r4->length;
	if( r3 >= r5 ) goto label$e26c8ce_1_21;
	r5 = r4->length;
	if( ((unsigned)r3) < ((unsigned)r5) ) goto label$e26c8ce_1_12;
	r6 = NULL;
	goto label$e26c8ce_1_15;
	label$e26c8ce_1_12:
	r8 = r4->array;
	r7 = ((vdynamic**)(r8 + 1))[r3];
	r6 = (venum*)r7;
	label$e26c8ce_1_15:
	++r3;
	if( r1 == NULL ) hl_null_access();
	r9 = (String)s$_Called_from_;
	StringBuf_add(r1,((vdynamic*)r9));
	haxe__CallStack_CallStack_Impl__itemToString(r1,r6);
	goto label$e26c8ce_1_4;
	label$e26c8ce_1_21:
	if( r1 == NULL ) hl_null_access();
	r9 = StringBuf_toString(r1);
	return r9;
}

hl__types__ArrayObj haxe__CallStack_CallStack_Impl__subtract(hl__types__ArrayObj r0,hl__types__ArrayObj r1) {
	hl__types__ArrayObj r5;
	venum *r11, *r14;
	bool r9;
	hl__types__ArrayBase r15;
	vdynamic *r12, *r16;
	varray *r13;
	int r2, r3, r4, r6, r7, r8, r10;
	r2 = -1;
	r3 = -1;
	label$e26c8ce_2_2:
	++r3;
	if( r0 == NULL ) hl_null_access();
	r4 = r0->length;
	if( r3 >= r4 ) goto label$e26c8ce_2_47;
	r4 = 0;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->length;
	label$e26c8ce_2_10:
	if( r4 >= r6 ) goto label$e26c8ce_2_43;
	r7 = r4;
	++r4;
	if( r0 == NULL ) hl_null_access();
	r10 = r0->length;
	if( ((unsigned)r3) < ((unsigned)r10) ) goto label$e26c8ce_2_19;
	r11 = NULL;
	goto label$e26c8ce_2_22;
	label$e26c8ce_2_19:
	r13 = r0->array;
	r12 = ((vdynamic**)(r13 + 1))[r3];
	r11 = (venum*)r12;
	label$e26c8ce_2_22:
	if( r1 == NULL ) hl_null_access();
	r10 = r1->length;
	if( ((unsigned)r7) < ((unsigned)r10) ) goto label$e26c8ce_2_27;
	r14 = NULL;
	goto label$e26c8ce_2_30;
	label$e26c8ce_2_27:
	r13 = r1->array;
	r12 = ((vdynamic**)(r13 + 1))[r7];
	r14 = (venum*)r12;
	label$e26c8ce_2_30:
	r9 = haxe__CallStack_CallStack_Impl__equalItems(r11,r14);
	if( !r9 ) goto label$e26c8ce_2_40;
	r10 = 0;
	if( r2 >= r10 ) goto label$e26c8ce_2_35;
	r2 = r3;
	label$e26c8ce_2_35:
	++r3;
	r10 = r0->length;
	if( r3 < r10 ) goto label$e26c8ce_2_39;
	goto label$e26c8ce_2_43;
	label$e26c8ce_2_39:
	goto label$e26c8ce_2_42;
	label$e26c8ce_2_40:
	r8 = -1;
	r2 = r8;
	label$e26c8ce_2_42:
	goto label$e26c8ce_2_10;
	label$e26c8ce_2_43:
	r6 = 0;
	if( r2 < r6 ) goto label$e26c8ce_2_46;
	goto label$e26c8ce_2_47;
	label$e26c8ce_2_46:
	goto label$e26c8ce_2_2;
	label$e26c8ce_2_47:
	r6 = 0;
	if( r2 < r6 ) goto label$e26c8ce_2_55;
	if( r0 == NULL ) hl_null_access();
	r4 = 0;
	r16 = hl_alloc_dynamic(&t$_i32);
	r16->v.i = r2;
	r15 = hl_types_ArrayObj_slice(r0,r4,r16);
	r5 = (hl__types__ArrayObj)hl_dyn_castp(&r15,&t$hl_types_ArrayBase,&t$hl_types_ArrayObj);
	return r5;
	label$e26c8ce_2_55:
	return r0;
}

bool haxe__CallStack_CallStack_Impl__equalItems(venum* r0,venum* r1) {
	String r6, r7, r8, r9;
	venum *r2, *r10;
	bool r3;
	vdynamic *r11, *r12;
	int r4, r5;
	if( r0 ) goto label$e26c8ce_3_6;
	if( r1 ) goto label$e26c8ce_3_4;
	r3 = true;
	return r3;
	label$e26c8ce_3_4:
	r3 = false;
	return r3;
	label$e26c8ce_3_6:
	if( r0 == NULL ) hl_null_access();
	r4 = HL__ENUM_INDEX__(r0);
	switch(r4) {
		default:
			goto label$e26c8ce_3_98;
		case 0:
			if( r1 ) goto label$e26c8ce_3_13;
			r3 = false;
			return r3;
			label$e26c8ce_3_13:
			if( r1 == NULL ) hl_null_access();
			r4 = HL__ENUM_INDEX__(r1);
			r5 = 0;
			if( r4 != r5 ) goto label$e26c8ce_3_19;
			r3 = true;
			return r3;
			label$e26c8ce_3_19:
			r3 = false;
			return r3;
		case 1:
			if( r1 ) goto label$e26c8ce_3_24;
			r3 = false;
			return r3;
			label$e26c8ce_3_24:
			if( r1 == NULL ) hl_null_access();
			r4 = HL__ENUM_INDEX__(r1);
			r5 = 1;
			if( r4 != r5 ) goto label$e26c8ce_3_35;
			r6 = ((haxe_StackItem_Module*)r1)->p0;
			r7 = ((haxe_StackItem_Module*)r0)->p0;
			if( r7 == r6 || (r7 && r6 && String___compare(r7,(vdynamic*)r6) == 0) ) goto label$e26c8ce_3_33;
			r3 = false;
			goto label$e26c8ce_3_34;
			label$e26c8ce_3_33:
			r3 = true;
			label$e26c8ce_3_34:
			return r3;
			label$e26c8ce_3_35:
			r3 = false;
			return r3;
		case 2:
			if( r1 ) goto label$e26c8ce_3_40;
			r3 = false;
			return r3;
			label$e26c8ce_3_40:
			if( r1 == NULL ) hl_null_access();
			r4 = HL__ENUM_INDEX__(r1);
			r5 = 2;
			if( r4 != r5 ) goto label$e26c8ce_3_59;
			r2 = ((haxe_StackItem_FilePos*)r1)->p0;
			r6 = ((haxe_StackItem_FilePos*)r1)->p1;
			r4 = ((haxe_StackItem_FilePos*)r1)->p2;
			r11 = ((haxe_StackItem_FilePos*)r1)->p3;
			r12 = ((haxe_StackItem_FilePos*)r0)->p3;
			r5 = ((haxe_StackItem_FilePos*)r0)->p2;
			r7 = ((haxe_StackItem_FilePos*)r0)->p1;
			r10 = ((haxe_StackItem_FilePos*)r0)->p0;
			if( r7 != r6 && (!r7 || !r6 || String___compare(r7,(vdynamic*)r6) != 0) ) goto label$e26c8ce_3_57;
			if( r5 != r4 ) goto label$e26c8ce_3_57;
			if( r12 != r11 && (!r12 || !r11 || (r12->v.i != r11->v.i)) ) goto label$e26c8ce_3_57;
			r3 = haxe__CallStack_CallStack_Impl__equalItems(r10,r2);
			return r3;
			label$e26c8ce_3_57:
			r3 = false;
			return r3;
			label$e26c8ce_3_59:
			r3 = false;
			return r3;
		case 3:
			if( r1 ) goto label$e26c8ce_3_64;
			r3 = false;
			return r3;
			label$e26c8ce_3_64:
			if( r1 == NULL ) hl_null_access();
			r4 = HL__ENUM_INDEX__(r1);
			r5 = 3;
			if( r4 != r5 ) goto label$e26c8ce_3_80;
			r6 = ((haxe_StackItem_Method*)r1)->p0;
			r7 = ((haxe_StackItem_Method*)r1)->p1;
			r8 = ((haxe_StackItem_Method*)r0)->p1;
			r9 = ((haxe_StackItem_Method*)r0)->p0;
			if( r9 != r6 && (!r9 || !r6 || String___compare(r9,(vdynamic*)r6) != 0) ) goto label$e26c8ce_3_78;
			if( r8 == r7 || (r8 && r7 && String___compare(r8,(vdynamic*)r7) == 0) ) goto label$e26c8ce_3_76;
			r3 = false;
			goto label$e26c8ce_3_77;
			label$e26c8ce_3_76:
			r3 = true;
			label$e26c8ce_3_77:
			return r3;
			label$e26c8ce_3_78:
			r3 = false;
			return r3;
			label$e26c8ce_3_80:
			r3 = false;
			return r3;
		case 4:
			if( r1 ) goto label$e26c8ce_3_85;
			r3 = false;
			return r3;
			label$e26c8ce_3_85:
			if( r1 == NULL ) hl_null_access();
			r4 = HL__ENUM_INDEX__(r1);
			r5 = 4;
			if( r4 != r5 ) goto label$e26c8ce_3_96;
			r11 = ((haxe_StackItem_LocalFunction*)r1)->p0;
			r12 = ((haxe_StackItem_LocalFunction*)r0)->p0;
			if( r12 == r11 || (r12 && r11 && (r12->v.i == r11->v.i)) ) goto label$e26c8ce_3_94;
			r3 = false;
			goto label$e26c8ce_3_95;
			label$e26c8ce_3_94:
			r3 = true;
			label$e26c8ce_3_95:
			return r3;
			label$e26c8ce_3_96:
			r3 = false;
			return r3;
	}
	label$e26c8ce_3_98:
	r3 = false;
	return r3;
}

void haxe__CallStack_CallStack_Impl__itemToString(StringBuf r0,venum* r1) {
	String r5, r6, r9;
	venum *r4;
	vdynamic *r7, *r8;
	int r3;
	if( r1 == NULL ) hl_null_access();
	r3 = HL__ENUM_INDEX__(r1);
	switch(r3) {
		default:
			goto label$e26c8ce_4_54;
		case 0:
			if( r0 == NULL ) hl_null_access();
			r5 = (String)s$a_C_function;
			StringBuf_add(r0,((vdynamic*)r5));
			goto label$e26c8ce_4_54;
		case 1:
			r5 = ((haxe_StackItem_Module*)r1)->p0;
			if( r0 == NULL ) hl_null_access();
			r6 = (String)s$module_;
			StringBuf_add(r0,((vdynamic*)r6));
			StringBuf_add(r0,((vdynamic*)r5));
			goto label$e26c8ce_4_54;
		case 2:
			r4 = ((haxe_StackItem_FilePos*)r1)->p0;
			r5 = ((haxe_StackItem_FilePos*)r1)->p1;
			r3 = ((haxe_StackItem_FilePos*)r1)->p2;
			r7 = ((haxe_StackItem_FilePos*)r1)->p3;
			if( !r4 ) goto label$e26c8ce_4_23;
			haxe__CallStack_CallStack_Impl__itemToString(r0,r4);
			if( r0 == NULL ) hl_null_access();
			r6 = (String)s$bbee82c;
			StringBuf_add(r0,((vdynamic*)r6));
			label$e26c8ce_4_23:
			if( r0 == NULL ) hl_null_access();
			StringBuf_add(r0,((vdynamic*)r5));
			r6 = (String)s$_line_;
			StringBuf_add(r0,((vdynamic*)r6));
			r8 = hl_alloc_dynamic(&t$_i32);
			r8->v.i = r3;
			StringBuf_add(r0,((vdynamic*)r8));
			if( !r7 ) goto label$e26c8ce_4_33;
			r6 = (String)s$_column_;
			StringBuf_add(r0,((vdynamic*)r6));
			StringBuf_add(r0,((vdynamic*)r7));
			label$e26c8ce_4_33:
			if( !r4 ) goto label$e26c8ce_4_36;
			r6 = (String)s$9371d7a;
			StringBuf_add(r0,((vdynamic*)r6));
			label$e26c8ce_4_36:
			goto label$e26c8ce_4_54;
		case 3:
			r5 = ((haxe_StackItem_Method*)r1)->p0;
			r6 = ((haxe_StackItem_Method*)r1)->p1;
			if( r0 == NULL ) hl_null_access();
			if( r5 ) goto label$e26c8ce_4_43;
			r9 = (String)s$2f6bac6;
			goto label$e26c8ce_4_44;
			label$e26c8ce_4_43:
			r9 = r5;
			label$e26c8ce_4_44:
			StringBuf_add(r0,((vdynamic*)r9));
			r9 = (String)s$5058f1a;
			StringBuf_add(r0,((vdynamic*)r9));
			StringBuf_add(r0,((vdynamic*)r6));
			goto label$e26c8ce_4_54;
		case 4:
			r7 = ((haxe_StackItem_LocalFunction*)r1)->p0;
			if( r0 == NULL ) hl_null_access();
			r5 = (String)s$local_function_;
			StringBuf_add(r0,((vdynamic*)r5));
			StringBuf_add(r0,((vdynamic*)r7));
	}
	label$e26c8ce_4_54:
	return;
}

