// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe___CallStack__CallStack_Impl_
#define INC_haxe___CallStack__CallStack_Impl_
typedef struct _haxe___CallStack__$CallStack_Impl_ *haxe___CallStack__$CallStack_Impl_;
typedef struct _haxe___CallStack__CallStack_Impl_ *haxe___CallStack__CallStack_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <haxe/StackItem.h>
#include <_std/StringBuf.h>


struct _haxe___CallStack__$CallStack_Impl_ {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* toString;
	vclosure* subtract;
	vclosure* equalItems;
	vclosure* itemToString;
};
struct _haxe___CallStack__CallStack_Impl_ {
	hl_type *$type;
};
#endif

