// Generated by Haxe 4.3.1
#ifndef INCLUDED_vision_exceptions_MatrixOperationError
#define INCLUDED_vision_exceptions_MatrixOperationError

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_vision_exceptions_VisionException
#include <vision/exceptions/VisionException.h>
#endif
HX_DECLARE_CLASS1(haxe,Exception)
HX_DECLARE_CLASS2(vision,ds,Array2D)
HX_DECLARE_CLASS2(vision,exceptions,MatrixOperationError)
HX_DECLARE_CLASS2(vision,exceptions,VisionException)

namespace vision{
namespace exceptions{


class HXCPP_CLASS_ATTRIBUTES MatrixOperationError_obj : public  ::vision::exceptions::VisionException_obj
{
	public:
		typedef  ::vision::exceptions::VisionException_obj super;
		typedef MatrixOperationError_obj OBJ_;
		MatrixOperationError_obj();

	public:
		enum { _hx_ClassId = 0x122b8ece };

		void __construct(::String op,::Array< ::Dynamic> matrices,int offense);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="vision.exceptions.MatrixOperationError")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"vision.exceptions.MatrixOperationError"); }
		static ::hx::ObjectPtr< MatrixOperationError_obj > __new(::String op,::Array< ::Dynamic> matrices,int offense);
		static ::hx::ObjectPtr< MatrixOperationError_obj > __alloc(::hx::Ctx *_hx_ctx,::String op,::Array< ::Dynamic> matrices,int offense);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~MatrixOperationError_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("MatrixOperationError",62,90,c2,c0); }

		static ::String errorByType(::String type,::Array< ::Dynamic> mats,int off);
		static ::Dynamic errorByType_dyn();

};

} // end namespace vision
} // end namespace exceptions

#endif /* INCLUDED_vision_exceptions_MatrixOperationError */ 
