// Generated by Haxe 4.3.1
#ifndef INCLUDED_vision_ds_Line2D
#define INCLUDED_vision_ds_Line2D

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(vision,ds,Line2D)
HX_DECLARE_CLASS2(vision,ds,Point2D)
HX_DECLARE_CLASS2(vision,ds,Ray2D)

namespace vision{
namespace ds{


class HXCPP_CLASS_ATTRIBUTES Line2D_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Line2D_obj OBJ_;
		Line2D_obj();

	public:
		enum { _hx_ClassId = 0x6048be01 };

		void __construct( ::vision::ds::Point2D start, ::vision::ds::Point2D end);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="vision.ds.Line2D")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"vision.ds.Line2D"); }
		static ::hx::ObjectPtr< Line2D_obj > __new( ::vision::ds::Point2D start, ::vision::ds::Point2D end);
		static ::hx::ObjectPtr< Line2D_obj > __alloc(::hx::Ctx *_hx_ctx, ::vision::ds::Point2D start, ::vision::ds::Point2D end);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Line2D_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Line2D",e6,9c,34,21); }

		static  ::vision::ds::Line2D fromRay2D( ::vision::ds::Ray2D ray);
		static ::Dynamic fromRay2D_dyn();

		Float length;
		Float slope;
		Float degrees;
		Float radians;
		 ::vision::ds::Point2D start;
		 ::vision::ds::Point2D end;
		Float get_length();
		::Dynamic get_length_dyn();

		 ::vision::ds::Point2D intersect( ::vision::ds::Line2D line);
		::Dynamic intersect_dyn();

		Float distanceTo( ::vision::ds::Line2D line);
		::Dynamic distanceTo_dyn();

		virtual ::String toString();
		::Dynamic toString_dyn();

		 ::vision::ds::Ray2D toRay2D();
		::Dynamic toRay2D_dyn();

		 ::vision::ds::Point2D set_start( ::vision::ds::Point2D value);
		::Dynamic set_start_dyn();

		 ::vision::ds::Point2D set_end( ::vision::ds::Point2D value);
		::Dynamic set_end_dyn();

		 ::vision::ds::Point2D get_middle();
		::Dynamic get_middle_dyn();

		 ::vision::ds::Point2D set_middle( ::vision::ds::Point2D value);
		::Dynamic set_middle_dyn();

};

} // end namespace vision
} // end namespace ds

#endif /* INCLUDED_vision_ds_Line2D */ 
