// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__tools__ImageTools
#define INC_vision__tools__ImageTools
typedef struct _vision__tools__$ImageTools *vision__tools__$ImageTools;
typedef struct _vision__tools__ImageTools *vision__tools__ImageTools;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Bytes.h>
#include <vision/ds/Array2D.h>


struct _vision__tools__$ImageTools {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	int defaultResizeAlgorithm;
	vclosure* loadFromFile;
	vclosure* saveToFile;
	vclosure* addToScreen;
	vclosure* getNeighborsOfPixel;
	vclosure* grayscalePixel;
};
struct _vision__tools__ImageTools {
	hl_type *$type;
};
#endif

