// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_sys__thread__Lock
#define INC_sys__thread__Lock
typedef struct _sys__thread__$Lock *sys__thread__$Lock;
typedef struct _sys__thread__Lock *sys__thread__Lock;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>


struct _sys__thread__$Lock {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _sys__thread__Lock {
	hl_type *$type;
	hl_lock* handle;
};
#endif

