// Generated by Haxe 4.3.4
#ifndef INCLUDED_vision_ds_Queue_String
#define INCLUDED_vision_ds_Queue_String

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(vision,ds,QueueCell_String)
HX_DECLARE_CLASS2(vision,ds,Queue_String)

namespace vision{
namespace ds{


class HXCPP_CLASS_ATTRIBUTES Queue_String_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Queue_String_obj OBJ_;
		Queue_String_obj();

	public:
		enum { _hx_ClassId = 0x012bf362 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="vision.ds.Queue_String")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"vision.ds.Queue_String"); }
		static ::hx::ObjectPtr< Queue_String_obj > __new();
		static ::hx::ObjectPtr< Queue_String_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Queue_String_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Queue_String",3f,b1,11,3e); }

		int length;
		 ::vision::ds::QueueCell_String first;
		 ::Dynamic iterator();
		::Dynamic iterator_dyn();

		::String dequeue();
		::Dynamic dequeue_dyn();

		::String enqueue(::String value);
		::Dynamic enqueue_dyn();

		bool has(::String value);
		::Dynamic has_dyn();

		virtual ::String toString();
		::Dynamic toString_dyn();

		 ::vision::ds::QueueCell_String get_last();
		::Dynamic get_last_dyn();

		 ::vision::ds::QueueCell_String set_last( ::vision::ds::QueueCell_String value);
		::Dynamic set_last_dyn();

};

} // end namespace vision
} // end namespace ds

#endif /* INCLUDED_vision_ds_Queue_String */ 
