// Generated by Haxe 4.3.3
#ifndef INCLUDED_vision_ds_QueueCell
#define INCLUDED_vision_ds_QueueCell

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_b4dcd5c6f0f87e5e_11_new)
HX_DECLARE_CLASS2(vision,ds,QueueCell)

namespace vision{
namespace ds{


class HXCPP_CLASS_ATTRIBUTES QueueCell_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef QueueCell_obj OBJ_;
		QueueCell_obj();

	public:
		enum { _hx_ClassId = 0x65c00d5c };

		void __construct( ::Dynamic value, ::vision::ds::QueueCell next, ::vision::ds::QueueCell previous);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="vision.ds.QueueCell")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"vision.ds.QueueCell"); }

		inline static ::hx::ObjectPtr< QueueCell_obj > __new( ::Dynamic value, ::vision::ds::QueueCell next, ::vision::ds::QueueCell previous) {
			::hx::ObjectPtr< QueueCell_obj > __this = new QueueCell_obj();
			__this->__construct(value,next,previous);
			return __this;
		}

		inline static ::hx::ObjectPtr< QueueCell_obj > __alloc(::hx::Ctx *_hx_ctx, ::Dynamic value, ::vision::ds::QueueCell next, ::vision::ds::QueueCell previous) {
			QueueCell_obj *__this = (QueueCell_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(QueueCell_obj), true, "vision.ds.QueueCell"));
			*(void **)__this = QueueCell_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_b4dcd5c6f0f87e5e_11_new)
HXLINE(  12)		( ( ::vision::ds::QueueCell)(__this) )->previous = previous;
HXLINE(  13)		( ( ::vision::ds::QueueCell)(__this) )->value = value;
HXLINE(  14)		( ( ::vision::ds::QueueCell)(__this) )->next = next;
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~QueueCell_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("QueueCell",b3,57,38,66); }

		 ::vision::ds::QueueCell previous;
		 ::Dynamic value;
		 ::vision::ds::QueueCell next;
		 ::Dynamic getValue();
		::Dynamic getValue_dyn();

};

} // end namespace vision
} // end namespace ds

#endif /* INCLUDED_vision_ds_QueueCell */ 
