// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_vision__exceptions__LibraryRequired
#define INC_vision__exceptions__LibraryRequired
typedef struct _vision__exceptions__$LibraryRequired *vision__exceptions__$LibraryRequired;
typedef struct _vision__exceptions__LibraryRequired *vision__exceptions__LibraryRequired;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <vision/exceptions/VisionException.h>
#include <haxe/Exception.h>


struct _vision__exceptions__$LibraryRequired {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* getInclusionMethod;
};
struct _vision__exceptions__LibraryRequired {
	hl_type *$type;
	String _hx___exceptionMessage;
	hl__types__ArrayObj _hx___exceptionStack;
	varray* _hx___nativeStack;
	int _hx___skipStack;
	vdynamic* _hx___nativeException;
	haxe__Exception _hx___previousException;
};
#endif

