// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <vision/exceptions/MultithreadFailure.h>
extern String s$Thread_number_;
#include <hl/natives.h>
String String___alloc__(vbyte*,int);
String String___add__(String,String);
extern String s$_failed_;
String Std_string(vdynamic*);
extern String s$Multithreading_Failure;
void vision_exceptions_VisionException_new(vision__exceptions__VisionException,String,String);

void vision_exceptions_MultithreadFailure_new(vision__exceptions__MultithreadFailure r0,int r1,vdynamic* r2) {
	String r4, r8;
	int *r6;
	vbyte *r7;
	int r5;
	r4 = (String)s$Thread_number_;
	r5 = r1;
	r6 = &r5;
	r7 = hl_itos(r5,r6);
	r8 = String___alloc__(r7,r5);
	r4 = String___add__(r4,r8);
	r8 = (String)s$_failed_;
	r4 = String___add__(r4,r8);
	r8 = Std_string(r2);
	r4 = String___add__(r4,r8);
	r8 = (String)s$Multithreading_Failure;
	vision_exceptions_VisionException_new(((vision__exceptions__VisionException)r0),r4,r8);
	r5 = r0->_hx___skipStack;
	++r5;
	r0->_hx___skipStack = r5;
	return;
}

