// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe__Exception
#define INC_haxe__Exception
typedef struct _haxe__$Exception *haxe__$Exception;
typedef struct _haxe__Exception *haxe__Exception;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>


struct _haxe__$Exception {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
	vclosure* caught;
};
struct _haxe__Exception {
	hl_type *$type;
	String _hx___exceptionMessage;
	hl__types__ArrayObj _hx___exceptionStack;
	varray* _hx___nativeStack;
	int _hx___skipStack;
	vdynamic* _hx___nativeException;
	haxe__Exception _hx___previousException;
};
#endif

