// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe__IMap
#define INC_haxe__IMap
typedef struct _haxe__$IMap *haxe__$IMap;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _haxe__$IMap {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
#endif

