// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/NativeStackTrace.h>
#include <hl/natives.h>
extern hl_type t$hl_symbol;
#include <_std/EReg.h>
#include <haxe/StackItem.h>
extern hl_type t$haxe_StackItem;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type t$EReg;
extern String s$e696748;
extern String s$;
void EReg_new(EReg,String,String);
extern String s$_fun_0_9_0_9_;
extern hl_type t$String;
bool EReg_match(EReg,String);
String EReg_matched(EReg,int);
vdynamic* Std_parseInt(String);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);

void haxe_NativeStackTrace_saveStack(vdynamic* r0) {
	return;
}

varray* haxe_NativeStackTrace_exceptionStack() {
	hl_type *r3;
	varray *r1;
	int r0, r2;
	r1 = NULL;
	r0 = hl_exception_stack_raw(r1);
	r3 = &t$hl_symbol;
	r1 = hl_alloc_array(r3,r0);
	r2 = hl_exception_stack_raw(r1);
	return r1;
}

hl__types__ArrayObj haxe_NativeStackTrace_toHaxe(varray* r0,int* r1) {
	String r9, r10, r21, r23;
	hl__types__ArrayObj r3;
	venum *r22;
	hl_type *r5;
	bool r20;
	EReg r8, r11;
	hl_symbol *r19;
	vdynamic *r24;
	vbyte *r12, *r18;
	varray *r4;
	int r2, r6, r13, r14, r15, r16, r17;
	if( r1 ) goto label$c0b5e0e_3_3;
	r2 = 0;
	goto label$c0b5e0e_3_4;
	label$c0b5e0e_3_3:
	r2 = *r1;
	label$c0b5e0e_3_4:
	r5 = &t$haxe_StackItem;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r3 = hl_types_ArrayObj_alloc(r4);
	r8 = (EReg)hl_alloc_obj(&t$EReg);
	r9 = (String)s$e696748;
	r10 = (String)s$;
	EReg_new(r8,r9,r10);
	r11 = (EReg)hl_alloc_obj(&t$EReg);
	r9 = (String)s$_fun_0_9_0_9_;
	r10 = (String)s$;
	EReg_new(r11,r9,r10);
	r6 = 1024;
	r12 = hl_alloc_bytes(r6);
	r13 = 0;
	r14 = r0->size;
	r15 = 1;
	r14 = r14 - r15;
	label$c0b5e0e_3_22:
	if( r13 >= r14 ) goto label$c0b5e0e_3_80;
	r15 = r13;
	++r13;
	if( r15 >= r2 ) goto label$c0b5e0e_3_28;
	goto label$c0b5e0e_3_22;
	label$c0b5e0e_3_28:
	r16 = r6;
	r19 = ((hl_symbol**)(r0 + 1))[r15];
	r1 = &r16;
	r18 = hl_resolve_symbol(r19,r12,r1);
	if( r18 ) goto label$c0b5e0e_3_34;
	goto label$c0b5e0e_3_22;
	label$c0b5e0e_3_34:
	r9 = (String)hl_alloc_obj(&t$String);
	r9->bytes = r18;
	r17 = 0;
	r17 = hl_ucs2length(r18,r17);
	r9->length = r17;
	if( r8 == NULL ) hl_null_access();
	r20 = EReg_match(r8,r9);
	if( !r20 ) goto label$c0b5e0e_3_58;
	if( r3 == NULL ) hl_null_access();
	r17 = 1;
	r21 = EReg_matched(r8,r17);
	r17 = 2;
	r23 = EReg_matched(r8,r17);
	r22 = hl_alloc_enum(&t$haxe_StackItem,3);
	((haxe_StackItem_Method*)r22)->p0 = r21;
	((haxe_StackItem_Method*)r22)->p1 = r23;
	r17 = 4;
	r21 = EReg_matched(r8,r17);
	r17 = 5;
	r23 = EReg_matched(r8,r17);
	r24 = Std_parseInt(r23);
	r17 = r24 ? r24->v.i : 0;
	r24 = NULL;
	{ venum *tmp;
	tmp = hl_alloc_enum(&t$haxe_StackItem,2);
	((haxe_StackItem_FilePos*)tmp)->p0 = r22;
	((haxe_StackItem_FilePos*)tmp)->p1 = r21;
	((haxe_StackItem_FilePos*)tmp)->p2 = r17;
	((haxe_StackItem_FilePos*)tmp)->p3 = r24;
	r22 = tmp; };
	r17 = hl_types_ArrayObj_push(r3,((vdynamic*)r22));
	goto label$c0b5e0e_3_79;
	label$c0b5e0e_3_58:
	if( r11 == NULL ) hl_null_access();
	r20 = EReg_match(r11,r9);
	if( !r20 ) goto label$c0b5e0e_3_76;
	if( r3 == NULL ) hl_null_access();
	r17 = 1;
	r21 = EReg_matched(r11,r17);
	r24 = Std_parseInt(r21);
	r22 = hl_alloc_enum(&t$haxe_StackItem,4);
	((haxe_StackItem_LocalFunction*)r22)->p0 = r24;
	r17 = 2;
	r21 = EReg_matched(r11,r17);
	r17 = 3;
	r23 = EReg_matched(r11,r17);
	r24 = Std_parseInt(r23);
	r17 = r24 ? r24->v.i : 0;
	r24 = NULL;
	{ venum *tmp;
	tmp = hl_alloc_enum(&t$haxe_StackItem,2);
	((haxe_StackItem_FilePos*)tmp)->p0 = r22;
	((haxe_StackItem_FilePos*)tmp)->p1 = r21;
	((haxe_StackItem_FilePos*)tmp)->p2 = r17;
	((haxe_StackItem_FilePos*)tmp)->p3 = r24;
	r22 = tmp; };
	r17 = hl_types_ArrayObj_push(r3,((vdynamic*)r22));
	goto label$c0b5e0e_3_79;
	label$c0b5e0e_3_76:
	if( r3 == NULL ) hl_null_access();
	r22 = hl_alloc_enum(&t$haxe_StackItem,1);
	((haxe_StackItem_Module*)r22)->p0 = r9;
	r17 = hl_types_ArrayObj_push(r3,((vdynamic*)r22));
	label$c0b5e0e_3_79:
	goto label$c0b5e0e_3_22;
	label$c0b5e0e_3_80:
	return r3;
}

