// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe__StackItem
#define INC_haxe__StackItem
typedef struct _haxe__$StackItem *haxe__$StackItem;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>
#include <haxe/StackItem.h>


struct _haxe__$StackItem {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___ename__;
	hl_bytes_map* _hx___emap__;
	hl__types__ArrayObj _hx___constructs__;
	varray* _hx___evalues__;
};
typedef struct {
	HL__ENUM_CONSTRUCT__
	String p0;
} haxe_StackItem_Module;
typedef struct {
	HL__ENUM_CONSTRUCT__
	venum* p0;
	String p1;
	int p2;
	vdynamic* p3;
} haxe_StackItem_FilePos;
typedef struct {
	HL__ENUM_CONSTRUCT__
	String p0;
	String p1;
} haxe_StackItem_Method;
typedef struct {
	HL__ENUM_CONSTRUCT__
	vdynamic* p0;
} haxe_StackItem_LocalFunction;
#endif

