// Generated by HLC 4.3.4 (HL v5)
#ifndef INC_haxe___Resource__ResourceContent
#define INC_haxe___Resource__ResourceContent
typedef struct _haxe___Resource__$ResourceContent *haxe___Resource__$ResourceContent;
typedef struct _haxe___Resource__ResourceContent *haxe___Resource__ResourceContent;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _haxe___Resource__$ResourceContent {
	hl_type *$type;
	hl_type* _hx___type__;
	vdynamic* _hx___meta__;
	varray* _hx___implementedBy__;
	String _hx___name__;
	vdynamic* _hx___constructor__;
};
struct _haxe___Resource__ResourceContent {
	hl_type *$type;
	vbyte* name;
	vbyte* data;
};
#endif

