// Generated by HLC 4.3.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <_std/EReg.h>
#include <hl/types/ArrayObj.h>
#include <hl/natives.h>
extern String s$g;
hl__types__ArrayObj String_split(String,String);
extern String s$;
String hl_types_ArrayObj_join(hl__types__ArrayObj,String);
extern hl_type t$_i32;
String String_substr(String,int,vdynamic*);

void EReg_new(EReg r0,String r1,String r2) {
	ereg *r10;
	String r4, r5;
	hl__types__ArrayObj r3;
	bool r7;
	vbyte *r11, *r12;
	int r8, r9;
	if( r2 == NULL ) hl_null_access();
	r5 = (String)s$g;
	r3 = String_split(r2,r5);
	if( r3 == NULL ) hl_null_access();
	r8 = r3->length;
	r9 = 1;
	if( r8 > r9 ) goto label$6d09180_1_9;
	r7 = false;
	goto label$6d09180_1_10;
	label$6d09180_1_9:
	r7 = true;
	label$6d09180_1_10:
	r0->global = r7;
	r7 = r0->global;
	if( !r7 ) goto label$6d09180_1_16;
	r4 = (String)s$;
	r4 = hl_types_ArrayObj_join(r3,r4);
	r2 = r4;
	label$6d09180_1_16:
	if( r1 == NULL ) hl_null_access();
	r11 = r1->bytes;
	if( r2 == NULL ) hl_null_access();
	r12 = r2->bytes;
	r10 = hl_regexp_new_options(r11,r12);
	r0->r = r10;
	return;
}

bool EReg_match(EReg r0,String r1) {
	String r5;
	ereg *r3;
	bool r2;
	int r6, r7;
	vbyte *r4;
	r3 = r0->r;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r6 = 0;
	r7 = r1->length;
	r2 = hl_regexp_match(r3,r4,r6,r7);
	if( !r2 ) goto label$6d09180_2_9;
	r0->last = r1;
	goto label$6d09180_2_11;
	label$6d09180_2_9:
	r5 = NULL;
	r0->last = r5;
	label$6d09180_2_11:
	return r2;
}

String EReg_matched(EReg r0,int r1) {
	String r7;
	ereg *r4;
	vdynamic *r8;
	int *r5;
	int r2, r3, r6;
	r2 = 0;
	r4 = r0->r;
	r5 = &r2;
	r3 = hl_regexp_matched_pos(r4,r1,r5);
	r6 = 0;
	if( r3 >= r6 ) goto label$6d09180_3_8;
	r7 = NULL;
	return r7;
	label$6d09180_3_8:
	r7 = r0->last;
	if( r7 == NULL ) hl_null_access();
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r2;
	r7 = String_substr(r7,r3,r8);
	return r7;
}

